### ISSUE TITLE
Sync bulk Moodle Accounts with Azure AD

### ISSUE THREAD

**Issue by harshvmcs** [microsoft/Learn-LTI#106]
Dear Team,

We have local accounts (approx. 9000 students and staff) created directly on Moodle and do not have any Active Directory server.
The MS Learn-LTI integration part worked fine, but now we need the users currently in Moodle to be synced with Azure AD so that students/staff can use the same credentials on Microsoft Learn portal too.

We need a guide / use case where we can push the Moodle users to Azure AD.

Thank you

**Comment by leestott** [comment]
Hi So you need to setup your Moodle implementation to support Azure Active Directory 

The two plugin for moodle you need are:
Authentication: Azure Active Directory https://moodle.org/plugins/auth_azuread
and 
Blocks: Azure Active Directory https://moodle.org/plugins/block_azuread

See 
https://moodle.org/plugins/browse.php?list=set&id=34 

You then simply ensure the students log into Microsoft Learn using the same credentials.

**Comment by leestott** [comment]
@harshvmcs 

Additionally if your using o365 for your users and AAD you could also consider using OpenID here is the openID moodle extension 
https://moodle.org/plugins/auth_oidc

OpenID Connect Authentication Plugin
The OpenID Connect plugin provides single-sign-on functionality using configurable identity providers, including Azure Active Directory. It is used as part of the Office 365 suite of plugins to connect to Azure Active Directory, but can be configured to provide SSO for other OpenID Connect providers as well.

This is part of the suite of Office 365 plugins for Moodle. https://moodle.org/plugins/browse.php?list=set&id=72

To follow active development on GitHub, click here. https://github.com/Microsoft/o365-moodle/

**Comment by harshvmcs** [comment]
@leestott 

Thank you for responding. So if I bulk create the 9000 Azure accounts for students and then sync the Moodle accounts to Azure accounts, will all student profile data on Moodle like test scores, contact preferences, etc. also get synced to respective Azure accounts?

**Comment by leestott** [comment]
@harshvmcs

So the account will be synced from an Authentication perspective all the learning records and learning status will be held in your LMS. You can the Azure Active Directory is simply an Authentication system to connect your users with the Learn LTI application and present the appropriate modules from Microsoft Learn.

**Comment by leestott** [comment]
@harshvmcs

Please ensure the users emails in AAD match the LMS user emails. We have seen recent issues where users emails in your LMS and AAD do not match you can receive a failure with the the tool as the email address with which the user was enrolled in the course was not the same as the AAD email- the casing being different.

Please ensure the email are the same and the case matches of the email.

**Comment by leestott** [comment]
@harshvmcs we are closing this issue as we havent had a response so believe the issue may of been resolved. If your still having issues please reach out.
