### ISSUE TITLE
User emails - Case Sensitivity

### ISSUE THREAD

**Issue by leestott** [microsoft/Learn-LTI#114]
# Bug
The bug is related to the user emails case sensitivity at present the users email within the LMS and Azure Active Directory has to match case. 

**Error from Debugging** 
Unauthorized error 
Get user details failed 
![image](https://user-images.githubusercontent.com/2511341/107367581-63cfae80-6ad7-11eb-96e0-4c515e350ea9.png)

**To Reproduce validate the issue**
Steps to check if this behavior is due to the email of the user being different in the LMS and Azure Active Directory:
1. Go to your LMS and check user account email address (example Moodle https://docs.moodle.org/310/en/Add_a_new_user#Email_address) 
2. Go to Azure Active Directory and check user account email address
3. Check case of user email in both systems
4. Update one system to reflect the case of the user email to ensure both system have the same case LOWER/Upper/Sentance

**Expected behavior**
Once the email is corrected the user can login and no errors are presented 
If the email are not the same the user is presented with a error 

see issues

**Comment by nehalilani** [comment]
A fix for this issue has been added in this [PullRequest](https://github.com/microsoft/Learn-LTI/pull/115)

**Comment by nehalilani** [comment]
@leestott 
The fix has been merged into main line. We can close this issue now.
