### ISSUE TITLE
Deployment fails with ParentResourceNotFound

### ISSUE THREAD

**Issue by cadi3s** [microsoft/Learn-LTI#116]
# Bug
Running the /deployment/run.bat script fails in step 6 with:

ERROR: Deployment failed. Correlation ID: 2094720e-1250-484e-b799-ca43c30d2da7. {
  "error": {
    "code": "ParentResourceNotFound",
    "message": "Can not perform requested operation on nested resource. Parent resource 'kv-ry2xvef66' not found."
  }
}

**To Reproduce**
See the attached transcript and log file.
[commandprompt.txt](https://github.com/microsoft/Learn-LTI/files/5967157/commandprompt.txt)
[Log-11-02-2021-17-23-22.log](https://github.com/microsoft/Learn-LTI/files/5967160/Log-11-02-2021-17-23-22.log)
[Transcript-11-02-2021-17-23-22.log](https://github.com/microsoft/Learn-LTI/files/5967162/Transcript-11-02-2021-17-23-22.log)

**Expected behavior**
It works!

**Desktop (please complete the following information):**
 - OS: W10
 - Browser n/a

**Comment by leestott** [comment]
Hi @cadi3s can you please delete the resource group which was created and then try to redeploy following the instructions at https://github.com/microsoft/Learn-LTI/blob/main/docs/DEPLOYMENT_GUIDE.md 

The error you provided simply says it cannot create the resources which has a previous dependency so you may not have selected an option. 

See https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/error-parent-resource

Also are you an Owner/Admin of the subscription?

**Comment by cadi3s** [comment]
Hi, I was following the DEPLOYMENT_GUIDE.md. The log/transscript/commandprompt files in the attachments show that there was a warning in step 4 of the deployment script, and an error in step 6. 
I was deploying to my MSDN (Developer) subscription, for which I am 'service administrator'.

The good news: after deleting the entire MSLearnLTI resource group, and trying exactly the same 'run.bat' again, it ran successfully. So, thanks for that tip :-)
