### ISSUE TITLE
Can open MS Learn Portal with specify user profile?

### ISSUE THREAD

**Issue by koolala** [microsoft/Learn-LTI#119]
**Question:**

- If user has more than 1 MS Learn Profile, the MS Learn portal may not use the desired user account as same as Moodle/Learn-LTI.
-- Have any setting can align the user profile on MS Learn portal? (Or let user know the user profile is not match)

Below is our reference case:
1. The Moodle and Learn-LTI Application can do the SSO and display correct user. 
![image](https://user-images.githubusercontent.com/3178741/111745328-65a34380-88c7-11eb-940d-5c29a4744581.png)

2. Click the link on the assignments to open MS Learn Portal. But the login profile is not match the LMS and Learn-LTI.
![image](https://user-images.githubusercontent.com/3178741/111745558-ba46be80-88c7-11eb-9843-7104dbb16e01.png)

3. Click sign-out button. And click sign-in to pickup another account.
![image](https://user-images.githubusercontent.com/3178741/111746708-59b88100-88c9-11eb-8b35-51d7d01163f0.png)

**Comment by leestott** [comment]
@koolala Yes this is correct the users should ideally be using Linked Profiles within Microsoft Learn. 

It is best practice to associate multiple MSA or Accounts to a single Learn profile. 

Linked Profile are really essential in Education as student will not always be student@domain.edu so this allows them to take their Learn Learning history with them and login with multiple accounts 

![LinkedProfile](https://user-images.githubusercontent.com/2511341/111884140-88148a00-89b7-11eb-9a4d-4864538c8490.png)
