### ISSUE TITLE
Logging in to Azure: Exception.Message

### ISSUE THREAD

**Issue by carsiemsft** [microsoft/Learn-LTI#123]
Hi, 

When I follow the very first step, once I clone the repo using Git it throws me the following error: 

[ 4/21/2021 8:36:20 AM ] - [INFO] - Logging in to Azure
[ 4/21/2021 8:36:20 AM ] - [ERROR] - Exception.Message [ The term 'az' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. ]
[ 4/21/2021 8:36:20 AM ] - [ERROR] - Exception.Type    [ System.Management.Automation.CommandNotFoundException ]
[ 4/21/2021 8:36:20 AM ] - [ERROR] - Error occurred while executing the Script. Please report the bug on Github (along with Error Message & Logs)

Then it throws me an error: 

![image](https://user-images.githubusercontent.com/30633677/115555876-03e74800-a27e-11eb-951b-19328f264d99.png)

**Comment by leestott** [comment]
@Carsiemsft so to run the install you need the Azure Command Line Extension tool installed see  Instructions at: https://docs.microsoft.com/cli/azure/install-azure-cli-windows?tabs=azure-cli for instructions. 

Once you have this install the AZ cmd link will work.

**Comment by carsiemsft** [comment]
Thanks so much, it worked!!! :)
