### ISSUE TITLE
Can not deploy the App on my Subscription

### ISSUE THREAD

**Issue by Ivan-Ada** [microsoft/Learn-LTI#124]
I am the owner of the subscription
It fails on the Step #4 Registering Azure AD App.
Have tried 2 times with 2 different regions
[Log-07-05-2021-09-43-57.log](https://github.com/microsoft/Learn-LTI/files/6440023/Log-07-05-2021-09-43-57.log)
[Log-07-05-2021-09-50-57.log](https://github.com/microsoft/Learn-LTI/files/6440024/Log-07-05-2021-09-50-57.log)

**Comment by Ivan-Ada** [comment]
@leestott 
thank you for your reply!

The subscription I used for deployment contained no resources related to LTI app at all. I have just tried to redeploy it on 2 another subscriptions, unfortunately with the same result (an the same error message):

Exception.Message [ Encountered an Error while creating AAD App ]
Exception.Type    [ System.Management.Automation.RuntimeException ]

**Comment by leestott** [comment]
Hi @Ivan-Ada

Thanks for confirming can you confirm you have these prerequisites

To begin, you will need the following installed. 

Azure CLI
DotNet Core SDK
Node.js
Powershell
Git

You will need a valid a Azure subscription

Can you confirm if your subscription has service Principal/Owner permissions of the Azure Subscription you are deploying too?

**Comment by leestott** [comment]
@Ivan-Ada

Regarding the error.. 
Could you please check with your AAD admin if you are are allowed to create app registrations?

**Comment by Ivan-Ada** [comment]
> @Ivan-Ada
> 
> Regarding the error..
> Could you please check with your AAD admin if you are are allowed to create app registrations?

@leestott 
I have just manually created an Dummy-AAD-app, thus I have the permissions required.

**Comment by Ivan-Ada** [comment]
@leestott 

below are the versions of the required libraries/apps I have installed:

Azure CLI: 		2.23.0
DotNet Core SDK: 	2.1.503 (x64)
Node.js: 			14.16.1 LTS
Powershell: 		7.1.3.0
Git:				2.20.0.windows.1 

the current version of DotNet Core is 3.1, should I upgrade mine?

**Comment by Ivan-Ada** [comment]
@leestott 
I have updated the software discussed and the next deployment seems to be successful, thank you!
However I am getting on the every deployment's step the error "DLL load failed while importing win32file: The specified module could not be found." it works.

**Comment by leestott** [comment]
@Ivan-Ada 

Hi did you manage to get the installation working? if so can we close this issue?

**Comment by Ivan-Ada** [comment]
@leestott 

yes it works, thank you so much!
