### ISSUE TITLE
deployment run.bat stop first step

### ISSUE THREAD

**Issue by ericfalcon** [microsoft/Learn-LTI#126]
# If this is about an issue in the guides

**Describe the issue**
When  run the run.bat file, powershell stop befor connect to azure count.
[Log-08-05-2021-22-53-53.log](https://github.com/microsoft/Learn-LTI/files/6446556/Log-08-05-2021-22-53-53.log)

**Comment by adbindal** [comment]
@ericfalcon, Seems like your Powershell isn't able to recognize `az` command and hence it is unable to trigger the script. Restarting the Powershell again might be of some help in this case. Also, I believe the prerequisites listed at https://github.com/microsoft/Learn-LTI/blob/main/docs/DEPLOYMENT_GUIDE.md#prerequisites are completed in your environment?

**Comment by leestott** [comment]
@ericfalcon did this resolve your issue?

To run the install you need the Azure Command Line Extension tool installed see Instructions at: https://docs.microsoft.com/cli/azure/install-azure-cli-windows?tabs=azure-cli for instructions.

Once you have this install the AZ cmd link will work

**Comment by leestott** [comment]
@ericfalcon Hi did the instructions unblock you and did you manage to get the LTI Application successfully installed? Can we close the issue?

**Comment by leestott** [comment]
@ericfalcon we have not had a response so presume updating the CLI tools has fixed your issue. Please reopen this issue if you still have a problem
