### ISSUE TITLE
Error during Step 10 - Installing the backend

### ISSUE THREAD

**Issue by atousey** [microsoft/Learn-LTI#131]
I received the following error during the Deploy.ps1 install:

Determining projects to restore...
C:\Users\atousey\Downloads\Learn-LTI\backend\Utils\Edna.Utils.Linq\Edna.Utils.Linq\Edna.Utils.Linq.csproj : error NU1100: Unable to resolve 'NETStandard.Library (>= 2.0.3)' for '.NETStandard,Version=v2.0'. [C:\Users\atousey\Downloads\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
  Failed to restore C:\Users\atousey\Downloads\Learn-LTI\backend\Utils\Edna.Utils.Linq\Edna.Utils.Linq\Edna.Utils.Linq.csproj (in 143 ms).
  Restored C:\Users\atousey\Downloads\Learn-LTI\backend\Bindings\Edna.Bindings.User\Edna.Bindings.User.csproj (in 8.21 sec).
  Restored C:\Users\atousey\Downloads\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj (in 8.21 sec).
  Restored C:\Users\atousey\Downloads\Learn-LTI\backend\Utils\Edna.Utils.Http\Edna.Utils.Http\Edna.Utils.Http.csproj (in 8.21 sec).
[ 5/24/2021 5:00:31 PM ] - [ERROR] - Exception.Message [ Errors while building Function App [ AssignmentLearnContent ] ]
[ 5/24/2021 5:00:31 PM ] - [ERROR] - Exception.Type    [ System.Management.Automation.RuntimeException ]
[ 5/24/2021 5:00:31 PM ] - [ERROR] - Error occurred while executing the Script. Please report the bug on Github (along with Error Message & Logs)

I am not sure what to do.

**Comment by leestott** [comment]
@atousey Hi Angela 

So the error looks like you have NOT installed the prerequisites of .NETcore SDK 

see https://github.com/microsoft/Learn-LTI/blob/main/docs/DEPLOYMENT_GUIDE.md

To begin, you will need:

## Prerequisites

To begin, you will need:
- [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest?WT.mc_id=learnlti-github-cxa)
- [DotNet Core SDK](https://dotnet.microsoft.com/download?WT.mc_id=learnlti-github-cxa)
- [Node.js](https://nodejs.org/en/download/)
- [Powershell](https://docs.microsoft.com/powershell/scripting/install/installing-powershell?view=powershell-7?WT.mc_id=learnlti-github-cxa)
- [Git](https://git-scm.com/downloads)
- An Azure subscription

**Comment by leestott** [comment]
@atousey did installing the prerequisites unblock you?

**Comment by atousey** [comment]
I had them installed, but I needed to restart my computer. Another package installed and needed restart. After the restart, it ran successfully.
