### ISSUE TITLE
LTI Integration with Mconnect not working

### ISSUE THREAD

**Issue by coachsbansal** [microsoft/Learn-LTI#133]
Dear team,

We integrated MS Learn LTI with our e-learning platform (Moodle) 2 months back. We faced some issues, but with your help it got resolved. It was working on Browser as well on Ms-Teams integrated with M-connect. But from last one day I am again finding the the issue. The Application is working fine on the Browser, but not on the Application function for M-connect. Getting below error {"Message":"Could not validate request."}

Kindly guide.

**Comment by leestott** [comment]
Hi @coachsbansal can you confirm if the m-connect is using a valid 3rd party SSL certificate for https traffic?

**Comment by coachsbansal** [comment]
Hi Lee, Sorry for the delay in response. Yes, there is a valid HTTPS certificate is available.

**Comment by leestott** [comment]
Hi @coachsbansal

So just to confirm are you using the Microsoft team Moodle connector https://docs.microsoft.com/microsoftteams/install-moodle-integration

If so can you provide some screenshots of the error? As you say the Learn LTI application Webapp is working OK so this is passing the token successfully. 

Also could you look at debugging the Azure function the error your getting looks like a auth issue from Moodle connect within team.  If you follow the troubleshooting guide for function debugging.

**Comment by coachsbansal** [comment]
Dear Lee,

Yes we are using Microsoft Teams and Moodle Connector from Scoolers.

Sure, I will share the screenshot along with few debugging findings for
your evaluation.

Regards

Sandeep Bansal

**Comment by leestott** [comment]
@coachsbansal  thanks for confirming your using https://skooler.com/mconnect/ we have NOT tested the solution using Skooler.

We have only tested with Direct LMS connections as per https://github.com/microsoft/Learn-LTI/blob/main/docs/ARCHITECTURE_OVERVIEW.md

If you can debugging the function log I have a suspicion it will identify a security mismatch as your calling the API from another services endpoint but interested to see what the log uncovers.

**Comment by coachsbansal** [comment]
Let me check and share with you

**Comment by leestott** [comment]
@coachsbansal  I am closing this issue as there has not been any update with your work with supporting Skooler please reopen this issue if you have progressed if you have successfully installed the solution to Skooler please make a pull request to update the configuration document to provide instructions for other skooler users https://github.com/microsoft/Learn-LTI/blob/main/docs/CONFIGURATION_GUIDE.md

**Comment by coachsbansal** [comment]
Thank you, for helping and closing the case.

regards

Sandeep Bansal
