### ISSUE TITLE
Doesnt appear the Tool Registration URL

### ISSUE THREAD

**Issue by domo536** [microsoft/Learn-LTI#136]
Hi, the CMD doesn't show the tool registration URL at the end of the step
![image](https://user-images.githubusercontent.com/85671043/121486263-92b54d00-ca03-11eb-8e3e-92ce1fab28b4.png)

Can someone help me to get the tool registration URL so I can proceed to the next step.

**Comment by leestott** [comment]
@domo536 

Please look at the Transcript ****.log file the error should be visible to why this the stopped in the log output.

If you still have issues please add the transcript output removing any Private details.

**Comment by domo536** [comment]
![image](https://user-images.githubusercontent.com/85671043/121498823-6273ab80-ca0f-11eb-8d5f-21afb13f64c6.png)
 This is the info in my transcript log file. Is it the TerminatingError() that causes me not to get the Tool Registration URL?

**Comment by leestott** [comment]
@domo536 

Hi So this is a simply deployment failure 

Simply run the following CLEANUP script to remove any orphan services which may of been deployed into your Azure Subscription https://github.com/microsoft/Learn-LTI/blob/main/deployment/Cleanup.ps1 

Then rerun the setup scripts as per https://github.com/microsoft/Learn-LTI/blob/main/docs/DEPLOYMENT_GUIDE.md 

Please ensure you have the Prerequisites installed and using the latest versions we have seen issues in the past where old version or prerequisites are not installed.

There are links to the following at https://github.com/microsoft/Learn-LTI/blob/main/docs/DEPLOYMENT_GUIDE.md
Azure CLI
DotNet Core SDK
Node.js
Powershell
Git
An Azure subscription

**Comment by leestott** [comment]
@domo536 

Please let us know if this fixed your issue and we can close the ticket

**Comment by domo536** [comment]
May I know how to run the Cleanup.ps1 file? It is a txt document when I open it.
![image](https://user-images.githubusercontent.com/85671043/121520384-6dd1d180-ca25-11eb-8f4c-53ee264cf0c0.png)

**Comment by domo536** [comment]
Hi Sir, I right-clicked the Cleanup.ps1 file and Run it with Powershell. I believe this is the correct way to run the ps1 file. After that, I rerun the setup scripts as per https://github.com/microsoft/Learn-LTI/blob/main/docs/DEPLOYMENT_GUIDE.md. However, I still get error(as below) but the error is a bit different than the previous one. 
![image](https://user-images.githubusercontent.com/85671043/121525747-4c73e400-ca2b-11eb-9b26-e300d75946c9.png)

Do you want me to share the entire Transcript Log here for you to easier know what is the problem?

**Comment by leestott** [comment]
@domo536 yes pleasse we need the transcript.log

**Comment by domo536** [comment]
![image](https://user-images.githubusercontent.com/85671043/121527855-75957400-ca2d-11eb-959e-91e890400b03.png)

[Transcript-10-06-2021-20-46-16.log](https://github.com/microsoft/Learn-LTI/files/6631496/Transcript-10-06-2021-20-46-16.log)

**Comment by leestott** [comment]
@domo536 

Ok thanks so its not undertaking stage 6 which the ARM deployment for the solution. 

Can you run the cleanup.bat again and try again.  https://github.com/microsoft/Learn-LTI/blob/main/deployment/cleanup.bat

**Comment by domo536** [comment]
Do I need to download it and run? Or It already cloned in this link "git clone https://github.com/microsoft/Learn-LTI.git"?

**Comment by domo536** [comment]
May I know how to download the cleanup.bat? Its my first time using GitHub

**Comment by domo536** [comment]
I guess right click it and save it is the way to download it? I did it and ran it, it opened my cmd and closed it immediately, is it how its work?

**Comment by leestott** [comment]
Hi @domo536 

So you need to download and save the file to the same location as the scripts and then just rerun it if from the same folder as the Cleanup.ps1

**Comment by domo536** [comment]
Okay, let me just try it

**Comment by domo536** [comment]
Aww Sir, I ran the cleanup.bat, it just open the cmd and close it immediately, I don't know is it they way how it works. After that, it seems doesn't work because when I copy paste the "git clone https://github.com/microsoft/Learn-LTI.git" into my Git Bash, it still shows the Learn-ITL is still there. When I run the run.bat, it also stuck at the Stage 6. May I know is there any other way to entirely remove everything and I just redo it again and see?

**Comment by leestott** [comment]
Hi @domo536

So yes your new to github what you need to do is simply pull from https://www.git-tower.com/learn/git/faq/git-pull-origin-master/

But I would suggest the following

Simply go to http://github.com/microsoft/learn-lti click download a zip

Unzip the folder
Go to the script folder
Run cleanup bat 
Then run the setup again

**Comment by leestott** [comment]
@domo536 no this isn't successful the deploy.ps1 has 12 steps for some reason the deployment is failing on step 6 which is the step where the actual services are deployed by a ARM template. 

Please delete the MSLearnLTI resource group from your subscription manually or run the cleanup.bat or cleanup.ps1 and then run the deployment again 

You should see see success for all 12 steps

The final step when complete will have this message.

"TOOL REGISTRATION URL (Please Copy, Required for Next Steps)
********
======== Successfully Deployed Resources to Azure ==========='
"Deployment Complete"

**Comment by domo536** [comment]
![image](https://user-images.githubusercontent.com/85671043/121853857-04eba180-cd24-11eb-8b16-e9a5fd8d0de4.png)
For a correct MSLearnLTI, does it show "Success" in the deployment section? Cuz currently I can see is "7 Failed"

**Comment by leestott** [comment]
@Domo536 

So the success will be shown in the powershell script output and you will be provided the Tool Registration URL etc 

So you need to delete the resource group Learn LTI from your subscription or run the cleanup script ensure you have all the prerequisites installed and rerun the setup. Simply following the instructions provided for this to fail you have missed some instructions. As the deployment works without any issues.

**Comment by leestott** [comment]
@domo536 As this was a user deployment issues and guidance has been provided on how to uninstall and redeploy I will close the issues if you encounter problems going forward please feel free to open up a new issues.
