### ISSUE TITLE
'No sufficient permissions to view this page' when accessing Platform Registration Page

### ISSUE THREAD

**Issue by Soloresq** [microsoft/Learn-LTI#138]
I just solved my problem with accessing the Platform Registration Page which cost me a lot of time, so I think this would be a great information for the troubleshooting section.

Problem:
Installed the Learn LTI application by execution of the run.bat file. Installation succeeded. Try to access the created Platform Registration Page results in 'No sufficient permissions to view this page'.

Solution:
Go to the 'platforms' azure function inside of the resource group which was just created.
Go to 'Configuration' at the left side
Have a look into the 'AllowedUsers' environment variable.
Verify the email address of the user you are logged in with is included in the environment variable (!THIS IS CASE SENSITIVE!)
If it does not match or exist, update the environment variable and save the change.
Wait a minute to let change take effect and retry! 

(In my case the email address was added there with capital first letters while the email address of my login user had lowercase)

**Comment by leestott** [comment]
@Soloresq Thanks I will update the troubleshooting guide.
