### ISSUE TITLE
LTI Integration and vanity URL

### ISSUE THREAD

**Issue by lstickdo** [microsoft/Learn-LTI#139]
I am trying to create the Canvas LTI integration. My url is https://ivytech.instructure.com  However all our students and faculty use our vanity url which is https://ivylearn.ivytech.edu

What should I use for tool registration parameters?

**Comment by leestott** [comment]
@lstickdo as per the instructions https://github.com/microsoft/Learn-LTI/blob/main/docs/CONFIGURATION_GUIDE.md please use  **https://ivytech.instructure.com** 

The following steps show how to register the parameters back in the Learn LTI application's registration page. If you are not the one who deployed the application, you need to provide these parameters to that person.

Open the tool registration page from your browser.
Enter the following information:
Display name: give the tool a name of your choice.
**Issuer: enter https://canvas.instructure.com**
JWK Set URL: enter https://[tenant-name].instructure.com/api/lti/security/jwks
Access Token URL: enter https://[tenant-name].instructure.com/login/oauth2/token
**Authorization URL: enter https://[tenant-name].instructure.com/api/lti/authorize_redirect NOTE: [tenant-name] is where your Canvas tenant name hosted by instructure. For example if the url of the LMS is https://canvas.instructure.com, then the [tenant-name] is "canvas". If you are using self-hosted Canvas, replace https://[tenant-name].instructure.com with your canvas URL.**
Client ID: enter "Client ID" from the LTI key registration.
Optionally, you can add your Institution name and logo on the registration page.
Click SAVE REGISTRATION.

**Comment by leestott** [comment]
@lstickdo did this help resolve your issue? Can you confirm if you have successfully installed the tool so we can close this issue?

**Comment by leestott** [comment]
Issue being closed as solution has been documented.
