### ISSUE TITLE
Do we have to have AD Connect to provide a success deployment of LTI?

### ISSUE THREAD

**Issue by nastya2090** [microsoft/Learn-LTI#144]
Thank you so much for so useful and detailed guide! It's very cool.
I have some trouble with a deployment process, please help me as you can )

At the first Guide "**Deployment Guide**" https://github.com/microsoft/Learn-LTI/blob/main/docs/DEPLOYMENT_GUIDE.md at the requirements section I see only this prerequisites: **Prerequisites**
To begin, you will need:

Azure CLI
DotNet Core SDK
Node.js
Powershell
Git
An Azure subscription 

There is no one words about **AD Connect**

When I started to execute third step "**Educator Guide**" https://github.com/microsoft/Learn-LTI/blob/main/docs/USER_GUIDE.md#Customize-Review-and-Publish-the-assignment I couldn't to execute **Microsoft Learn LTI application**. I have the same error like in this section **LTI Application Login error: You are not enrolled in this course** https://github.com/microsoft/Learn-LTI/blob/main/docs/TROUBLESHOOTING.md 
I look at the follow comment:

User not registered on the LMS or logged into Web Browser with the incorrect account

-**Ensure you are using an Azure AD connected account and logged into their web browser with the same account they used to sign into the LMS.**
-Please ensure that AAD sign for your LMS is enabled and you are signing into your LMS with a AAD account.
-The emails of the users in the LMS and AAD should match.
-Ensure the users are active on the course.

It's a problem for because I have no AD Domain to setup AD Connect and synchronize the users. Is it possible to use this scenario "**Microsoft Learn LTI Application**" without AD Connect.
What can I change (Maybe some thing of Microsoft Identity, App Registration or something else) in my deployment without AD Connect?

Thank you!
The best regards, 
Anastasia V

**Comment by leestott** [comment]
Hi @nastya2090 

So you simply need an Azure Activity Directory for the app to registered 

 As stated, the failure is in Users Function App which is not being able to find the user (signed-in via AAD) enrolled into the current course. To prove this theory, please check that the return code for /me API in the Chrome DevTools network tab is http204 (i.e. No-Content).

As a quick question, could you please let us know whether your tool is onboarded using LTI1.1 or LTI1.3?

In our experience, as I remember, the only case when this happens is when user signs into Learn-LTI app with an onmicrosoft.com account which does not map to the email of any of the enrolled users of the course.

Additionally, you could use the following steps to understand the Azure function behavior and help us with the more details on your issue.
Troubleshooting
Azure Function Traces
This should provide details related to the execution context and state of the function execution when it would've returned http204.

	Goto your Resource Group inside Azure and select Function App matching users-XXXXXXX.
	Select Functions Blade in Left Hand Pane. Select GetUserDetails afterwards.
	Choose Monitor Blade in LHP and you should see the Invocation Traces.
	Clicking on the failing trace should provide more details related to Server logs for that function invocation to help you.

Failures (Exceptions) in App Insights

	Go to your Resource Group inside Azure and select Application Insights resource matching users-XXXXXXX.
	Select Failures Blade in LHP and then choose Exceptions Tab.
	The subsequent screen should indicate any exceptions that were thrown as a part of function execution and should provide more insights into what might've gone wrong on server when executing GetUserDetails api.

**Comment by nastya2090** [comment]
Thanks for the answer! I'm using LIT 1.3. 
Actually i deployed resource **Bitnami LMS powered by Moodle™** LMS in Azure.
At this Moodle Console I created a new course and added resource to the course by guide **Configure the tool** (https://github.com/microsoft/Learn-LTI/blob/main/docs/CONFIGURATION_GUIDE.md#Moodle-LMS)

Dev
Failed to load resource: the server "myservername" responded with a status of 500 (Internal Server Error)
Failed to load resource: the server "myservername" responded with a status of 404 (The requested content does not exist.)

At the Mooldle Console i see the course and before I assigned users to this course (their emais - is exect like AAD, and it has a part  "onmicrosoft.com"

**About Azure Function user-xxxxxxxx** and **Application Insights user-xxxxxxx**

the log contains information about users on my AAD and ip server ) How can I send it only to you without everyone's attention?

Can I input logs to this text chat? Is it secure?

Thank you so much for the help,
Anastasia

**Comment by leestott** [comment]
@nastya2090 

So the issue is your not using as SSL certificate on the server your Moodle (LMS) environment requires a valid SSL certificate and Domain name. 

I can see from the logs your using http://xxx.xxx.xxx.xxx IP address 

The installation looks like a Bitnami moodle implementation so follow these guidelines to use a lets encrypt SSL https://docs.bitnami.com/azure/how-to/generate-install-lets-encrypt-ssl/ 

If you using a standard web server there a great tool for supporting installing SSL certs https://certbot.eff.org/lets-encrypt simply choose the web server and platform and it will give you instructions. 

If your LMS is hosted on moodle you can add a static DNS name which you can use to register the SSL against. https://docs.microsoft.com/azure/virtual-machines/create-fqdn

Reach out if you have any other issues learnlti@microsoft.com is the email to send private details including screen shots with confidential data.

**Comment by leestott** [comment]
@nastya2090  As discussed updating your apache config based on the error your getting https://github.com/microsoft/Learn-LTI/blob/main/docs/TROUBLESHOOTING.md#error-unauthorized-401-when-using-moodle resolved your issue. Thanks for the feedback I have made changes to https://github.com/microsoft/Learn-LTI/blob/main/docs/TROUBLESHOOTING.md and glad this is now working.

**Comment by nastya2090** [comment]
Thank you very much for the help!
