### ISSUE TITLE
Unable to copy Learn Modules between Canvas courses

### ISSUE THREAD

**Issue by joeperry8080** [microsoft/Learn-LTI#145]
# If this is about an issue in the guides

**Describe the issue**
My college uses master course shells for our courses so that online courses use the same content for every section. I have created a shell in Canvas that uses MS Learn LTI integrated content. When creating an assignment with the required modules in the Learn LTI I expect that the content would be made available in the Canvas shell is exported/copied to another course, but this is not happening. I worked briefly with Lee Stott via Teams and tried what was suggested, but this did not work. 

**Expected behavior**
I expect to create an assignment using the Learn LTI, add the required modules, and then be able to use the same assignment in another course. I did not "publish" the assignment at the suggestion of Lee, but this did not help. The only difference between the Canvas shells is that the master shell has several participants and the copied shell only has me as instructor/developer.

**Screenshot of the assignment in the master course:**
![master_course_assignment](https://user-images.githubusercontent.com/12789948/125369962-5f8c1380-e34b-11eb-8fe7-4ef2d213519d.JPG)

**Screenshot of the assignment in the copied course:**
![copied_course_assignment](https://user-images.githubusercontent.com/12789948/125369985-75013d80-e34b-11eb-8468-8b7e5e438280.JPG)

**Comment by leestott** [comment]
@joeperry8080 thanks let us look into this if you could email learnlti@microsoft.com with your details we will schedule a call.

**Comment by leestott** [comment]
@Joeperry8080 so at present this is NOT supported as the tool uses unique references to specific courses held within the LMS. 

We will look at this feature as an enhancement. If you could share with us a use case to why you like to have templated courses which use the Learn LTi? 

One of the reasons we thought this would NOT be  used was ensuring the most relevant module in Learn were presented to the learner  i.e. New or different available modules which would be better for the course which were NOT previously available when the initial/first course was run.

**Comment by leestott** [comment]
@Joeparry8080

We will investigate this further and add this as a feature request https://github.com/microsoft/Learn-LTI/issues/147
