### ISSUE TITLE
Microsoft Learn LTI in D2L Brightspace returning Error - currently unable to handle this request 

### ISSUE THREAD

**Issue by NShresthaonGH** [microsoft/Learn-LTI#155]
Dear Team,

We integrated Microsoft Learn LTI in our D2L Brighspace MLS. We have ran into some issues with the Integration. When we lunch the application from LMS, we received the following error on LMS side.

<img width="675" alt="0" src="https://user-images.githubusercontent.com/88966678/132120303-1011d10b-05a3-4157-8c44-d981e3804fd0.png">

At Azure side, we are getting the below error when trying to launch the application form our LMS it is hitting the “'LtiAdvantageLaunch’” Function and getting the below error. 

2021-08-05T06:54:24.213 [Information] Executing 'LtiAdvantageLaunch' (Reason='This function was programmatically called via the host APIs.', Id=0a53b2e7-fefa-4f8b-9509-98a88ea8cf12)

2021-08-05T06:54:24.369 [Error] Executed 'LtiAdvantageLaunch' (Failed, Id=0a53b2e7-fefa-4f8b-9509-98a88ea8cf12, Duration=325ms)Object reference not set to an instance of an object.

It would be greatly appreciated if you could point us in the right direction.
Thank you.

**Comment by leestott** [comment]
@NShresthaonGH thanks for the issue at present we only have installation documented for Moodle, canvas and Blackboard. I suggest you follow the troubleshooting guide and debug the Azure Functions and app insights to understand where the issue is with the D2L implementation. If you look at the OpenEdx issue #103 this may provide some more insights we need help documenting the implementation on D2L so any help in this would be greatly appreciated.

**Comment by leestott** [comment]
@NShresthaonGH  see https://github.com/microsoft/Learn-LTI/issues/68 @alphaz18 thanks for PR regarding the outh support for Brightspace D2L #156 so this may unblock you if you could validate this works.

**Comment by NShresthaonGH** [comment]
Hi Stephen,

This the recent email from GitHub.

Thank you.

Nabin Shrestha
eLearning Technical Specialist
Information Technology Services
Victoria University
Phone 03 9919 5163
***@***.***<https://www.vu.edu.au/>
***@***.***<https://www.facebook.com/victoria.university/>  ***@***.*** <https://au.linkedin.com/school/victoria-university/>  ***@***.*** <https://www.instagram.com/victoriauniversity/?hl=en>  ***@***.*** <https://twitter.com/victoriauninews?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor>  ***@***.*** <https://www.youtube.com/user/VictoriaUniversity>

CRICOS Provider No. 00124K (Melbourne)
CRICOS Provider No. 02475D (Sydney)
RTO Code. 3113

I acknowledge, respect and recognise the Boonwurrung and Woiwurrung of the Kulin as the Traditional Owners of University land.

This email and any files transmitted with it are confidential and are intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. Please note that any views or opinions presented in this email are solely those of the author and do not necessarily represent those of Victoria University.

Please consider the environment before printing this email.

**Comment by NShresthaonGH** [comment]
Hi @leestott, 

Thank you for providing us the information to troubleshoot out LTI situation. We went through the document but we could not find the correct information to rectify the situation.

However, we have made some changes in LMS interchanging URLs between Redirect UTLs and OpenID Connect Login URLs. This now produced new error in both Azure and LMS when we lunch the LTI in MLS.

Images below indicate the original setting in LMS and Original Error.

Setting at LMS:
<img width="596" alt="1" src="https://user-images.githubusercontent.com/88966678/132122592-87d67a52-1cab-4a22-8f61-6e75eddce2e3.png">

Error at LMS once lunch the LTI
<img width="675" alt="0" src="https://user-images.githubusercontent.com/88966678/132122602-8fd4ffcb-1d3a-4fae-bee5-92d83d63d66a.png">

Error received at Azure side:
<img width="916" alt="4" src="https://user-images.githubusercontent.com/88966678/132122617-b30236e3-4ae4-4693-8547-a402a75d2fc5.png">

After changes made in made LMS interchanging URLs between Redirect URLs and OpenID Connect Login URLs

Setting at LMS:
<img width="595" alt="2" src="https://user-images.githubusercontent.com/88966678/132122653-efdcd60a-5a11-45d5-a475-31c8e9d38caf.png">

Error at LMS once lunch the LTI
<img width="591" alt="3" src="https://user-images.githubusercontent.com/88966678/132122667-a92effe3-0a8a-450e-acac-ea8c678999cb.png">

Error received at Azure side:
<img width="922" alt="5" src="https://user-images.githubusercontent.com/88966678/132122675-bd9be484-6cea-4b74-9d17-192528a39ca0.png">

Any suggestions to rectify this situation would be greatly appreciated.
Thank you.

**Comment by leestott** [comment]
@NShresthaonGH so you need to use the forked code which is the following PR this will help us test and validate this works.

@alphaz89 has created a PR from their code base which has been modified to support D2L and also developed the instructions for installation it would be great for you to validate this.. https://github.com/microsoft/Learn-LTI/pull/156

**Comment by NShresthaonGH** [comment]
Hi @leestott and @alphaz18,

Thank you for your advice to download the source and install from repository https://github.com/alphaz18/Learn-LTI/tree/Add-Registration-Attribute-Audience to add Audience attribute. The code has been downloaded and redeployed the LTI on Azure. 
While configuring the LTI in LMS, we followed steps from https://github.com/alphaz18/Learn-LTI/blob/Add-Registration-Attribute-Audience/docs/CONFIGURATION_GUIDE.md for Brightspace LMS. At the time of Tool registration, we realized that the ‘Audience’ filed is missing.

<img width="417" alt="Registration" src="https://user-images.githubusercontent.com/88966678/133914728-79fa1ff1-326a-4980-8fef-0410388dd10d.png">

According to the steps mentioned in the article, there should be ‘Audience’ filed on Tool Registration page.

<img width="511" alt="Add-Registration-Attribute-Audience · alphaz" src="https://user-images.githubusercontent.com/88966678/133914751-942c4a94-c33a-48dd-b45d-db208d75400f.png">

But we proceeded and completed Tool registration without ‘Audience’ field.

Now, when we lunch LTI from LMS it tried to load assignment.

<img width="442" alt="Assignment Loading" src="https://user-images.githubusercontent.com/88966678/133914764-87afc80c-4624-4ec5-8cde-609cb1555900.png">

<img width="448" alt="Error Loading Assignment" src="https://user-images.githubusercontent.com/88966678/133914770-8a63c97c-9c97-4d55-9285-6d932e2d0289.png">

But it ends up with the error ‘Oops! Something went wrong’. We also realized that this error usually occurs when SSL certificate is not valid. We have valid SSL certificate in our environment but still receiving this error.

At Azure site, we found the following errors:

![666be333-4d8c-4cca-9feb-1d6bc8e3493e](https://user-images.githubusercontent.com/88966678/133914780-607b3504-4c1e-471d-8c6d-2b26af89e6d9.jpg)

![5554811e-8698-483b-a6df-247ddc05231a](https://user-images.githubusercontent.com/88966678/133914782-11793eec-6d40-4f68-80ec-2ad802c0f117.jpg)

Is this error indicating that Tool Registration is incomplete as ‘Audience’ filed was missing and is there a way to add this filed? It would be greatly appreciated if you could point us in the right direction.

Thank you for your help.

**Comment by alphaz18** [comment]
it looks like you may have missed the client code, how did you download the code and deploy it? you linked to the correct branch but seems the code you deployed may not contain the changes, in the code you downloaded please verify in file: "client/src/Features/Platform/PlatformRegistrationFields.ts" that the Audience field is in there, if it is not, then you may have the wrong code. 

If it is there, how did you deploy? normally you should just be able to use the run.bat. 

Regards,
alphaz18

**Comment by sjscicluna83** [comment]
@alphaz18  you were correct i downloaded the code in zip format and changing branches did not  update the code i needed to clone che repo down for this to work.

**Comment by NShresthaonGH** [comment]
@leestott and @alphaz18 thank you very much for you help and suggestions. LTI is now working  in our Brightspace environment. However, we needed to update user's email address in LMS to match with user's sign in for the application. As in our environment, email address of the user an sign in name do not match. Just would like to know whether it is possible to make this work even user's sign in and email address are different. Once again, thank you for your help.

Regards,
NShresthaonGH

**Comment by leestott** [comment]
@NShresthaonGH see https://github.com/microsoft/Learn-LTI/pull/158 for OpenEdx in relation to given name. @adbindal any comments? 

@NShresthaonGH  I think we you will need to add at least the user sign-in email into the AAD

**Comment by leestott** [comment]
@skmckenFVSD Please validate the brightspace installation as per @Alphaz18 instructions and code base see https://github.com/microsoft/Learn-LTI/pull/156

**Comment by leestott** [comment]
Brightspace D2L is now fully supported in the Learn LTI application
