### ISSUE TITLE
Error after deploy.ps1 step #10

### ISSUE THREAD

**Issue by renaldo-b** [microsoft/Learn-LTI#161]
Running into problems when deploy.ps1 reaches step #10. See the error output on the end.

Following is present on the system.
Microsoft .NET Core SDK 3.1.413 (x64)
Microsoft .NET SDK 5.0.302 )x64)
Node.js 14.17.6
Powershell 5.1.22000.1
Git 2.33

Error: 
=============================================================
STEP #10 - Installing the backend
=============================================================
PS C:\Code> TerminatingError(): "Errors while building Function App [ AssignmentLearnContent ]"
PS C:\Code> TerminatingError(): "Errors while building Function App [ AssignmentLearnContent ]"

I then tried to run publish.ps1. See all output from publish.ps1.

PS C:\Learn-lti\Learn-LTI\deployment> C:\Learn-lti\Learn-LTI\deployment\Publish.ps1
cmdlet Publish.ps1 at command pipeline position 1
Supply values for the following parameters:
ResourceGroupName: MSLearnLTI
AppName: MS-Learn-Lti-Tool-App

=============================================================
Gathering Deployment Info
=============================================================

[ 23-9-2021 14:06:18 ] - [INFO] - Validating App Registration
[ 23-9-2021 14:06:18 ] - [INFO] - Validating Resource Group
[ 23-9-2021 14:06:19 ] - [INFO] - Getting Function Apps Info
[ 23-9-2021 14:06:20 ] - [INFO] - Getting Static Website Info

=============================================================
Deployment Info Gathered
=============================================================

=============================================================
Installing the backend
=============================================================

[ 23-9-2021 14:06:21 ] - [INFO] - Switching to [../backend] as working directory
[ 23-9-2021 14:06:21 ] - [INFO] - Installing FunctionApp -- AssignmentLearnContent
[ 23-9-2021 14:06:21 ] - [INFO] - Publishing Project [ Edna.AssignmentLearnContent.csproj ] as FunctionApp
[ 23-9-2021 14:06:21 ] - [INFO] - Building [ C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent ] --> [ Artifacts\AssignmentLearnContent ]
[ 23-9-2021 14:06:22 ] - [INFO] -   Determining projects to restore...
C:\Learn-lti\Learn-LTI\backend\Utils\Edna.Utils.Linq\Edna.Utils.Linq\Edna.Utils.Linq.csproj : error NU1102: Unable to find package NETStandard.Library with version (>= 2.0.3) [C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.Assignme
ntLearnContent\Edna.AssignmentLearnContent.csproj]
C:\Learn-lti\Learn-LTI\backend\Utils\Edna.Utils.Linq\Edna.Utils.Linq\Edna.Utils.Linq.csproj : error NU1102:   - Found 1 version(s) in Microsoft Visual Studio Offline Packages [ Nearest version: 1.6.0 ] [C:\Learn-lti\Learn-LTI\backend\Functions\Edna.Assignmen
tLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj : error NU1101: Unable to find package AutoMapper.Extensions.Microsoft.DependencyInjection. No packages exist with this id in 
source(s): Microsoft Visual Studio Offline Packages
C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj : error NU1101: Unable to find package Microsoft.Azure.Functions.Extensions. No packages exist with this id in source(s): Micr
osoft Visual Studio Offline Packages
C:\Learn-lti\Learn-LTI\backend\Utils\Edna.Utils.Http\Edna.Utils.Http\Edna.Utils.Http.csproj : error NU1102: Unable to find package NETStandard.Library with version (>= 2.0.3) [C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.Assignme
ntLearnContent\Edna.AssignmentLearnContent.csproj]
C:\Learn-lti\Learn-LTI\backend\Utils\Edna.Utils.Http\Edna.Utils.Http\Edna.Utils.Http.csproj : error NU1102:   - Found 1 version(s) in Microsoft Visual Studio Offline Packages [ Nearest version: 1.6.0 ] [C:\Learn-lti\Learn-LTI\backend\Functions\Edna.Assignmen
tLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
C:\Learn-lti\Learn-LTI\backend\Bindings\Edna.Bindings.User\Edna.Bindings.User.csproj : error NU1102: Unable to find package NETStandard.Library with version (>= 2.0.3) [C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearn
Content\Edna.AssignmentLearnContent.csproj]
C:\Learn-lti\Learn-LTI\backend\Bindings\Edna.Bindings.User\Edna.Bindings.User.csproj : error NU1102:   - Found 1 version(s) in Microsoft Visual Studio Offline Packages [ Nearest version: 1.6.0 ] [C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnC
ontent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj : error NU1101: Unable to find package Microsoft.Azure.WebJobs.Extensions.Storage. No packages exist with this id in source(s)
: Microsoft Visual Studio Offline Packages
C:\Learn-lti\Learn-LTI\backend\Utils\Edna.Utils.Http\Edna.Utils.Http\Edna.Utils.Http.csproj : error NU1101: Unable to find package Microsoft.AspNetCore.Http.Features. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [C:\L
earn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
C:\Learn-lti\Learn-LTI\backend\Bindings\Edna.Bindings.User\Edna.Bindings.User.csproj : error NU1101: Unable to find package Microsoft.Azure.WebJobs.Extensions.Http. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [C:\Lea
rn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj : error NU1101: Unable to find package Microsoft.Extensions.Http. No packages exist with this id in source(s): Microsoft Visua
l Studio Offline Packages
C:\Learn-lti\Learn-LTI\backend\Utils\Edna.Utils.Http\Edna.Utils.Http\Edna.Utils.Http.csproj : error NU1101: Unable to find package Microsoft.Azure.Services.AppAuthentication. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packag
es [C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
C:\Learn-lti\Learn-LTI\backend\Bindings\Edna.Bindings.User\Edna.Bindings.User.csproj : error NU1101: Unable to find package Microsoft.Extensions.Http. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [C:\Learn-lti\Learn-L
TI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj : error NU1101: Unable to find package Microsoft.NET.Sdk.Functions. No packages exist with this id in source(s): Microsoft Vis
ual Studio Offline Packages
C:\Learn-lti\Learn-LTI\backend\Utils\Edna.Utils.Http\Edna.Utils.Http\Edna.Utils.Http.csproj : error NU1101: Unable to find package Microsoft.Extensions.DependencyInjection. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
 [C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
C:\Learn-lti\Learn-LTI\backend\Bindings\Edna.Bindings.User\Edna.Bindings.User.csproj : error NU1101: Unable to find package Microsoft.AspNetCore.Http.Features. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [C:\Learn-lt
i\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj : error NU1101: Unable to find package Microsoft.Azure.WebJobs.Extensions.Http. No packages exist with this id in source(s): M
icrosoft Visual Studio Offline Packages
C:\Learn-lti\Learn-LTI\backend\Utils\Edna.Utils.Http\Edna.Utils.Http\Edna.Utils.Http.csproj : error NU1101: Unable to find package Microsoft.Extensions.Http. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [C:\Learn-lti\
Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj : error NU1101: Unable to find package Microsoft.AspNetCore.Http.Features. No packages exist with this id in source(s): Micros
oft Visual Studio Offline Packages
C:\Learn-lti\Learn-LTI\backend\Bindings\Edna.Bindings.User\Edna.Bindings.User.csproj : error NU1101: Unable to find package Microsoft.Azure.Services.AppAuthentication. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [C:\
Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
C:\Learn-lti\Learn-LTI\backend\Utils\Edna.Utils.Http\Edna.Utils.Http\Edna.Utils.Http.csproj : error NU1101: Unable to find package Microsoft.Extensions.Logging.Abstractions. No packages exist with this id in source(s): Microsoft Visual Studio Offline Package
s [C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj : error NU1101: Unable to find package Microsoft.Azure.Services.AppAuthentication. No packages exist with this id in source(s)
: Microsoft Visual Studio Offline Packages
C:\Learn-lti\Learn-LTI\backend\Bindings\Edna.Bindings.User\Edna.Bindings.User.csproj : error NU1101: Unable to find package Microsoft.Extensions.DependencyInjection. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [C:\Le
arn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
C:\Learn-lti\Learn-LTI\backend\Utils\Edna.Utils.Http\Edna.Utils.Http\Edna.Utils.Http.csproj : error NU1101: Unable to find package System.IdentityModel.Tokens.Jwt. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [C:\Lear
n-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj : error NU1101: Unable to find package Microsoft.Extensions.DependencyInjection. No packages exist with this id in source(s): 
Microsoft Visual Studio Offline Packages
C:\Learn-lti\Learn-LTI\backend\Bindings\Edna.Bindings.User\Edna.Bindings.User.csproj : error NU1101: Unable to find package Microsoft.Extensions.Logging.Abstractions. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [C:\L
earn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj : error NU1101: Unable to find package Microsoft.Extensions.Logging.Abstractions. No packages exist with this id in source(s):
 Microsoft Visual Studio Offline Packages
C:\Learn-lti\Learn-LTI\backend\Bindings\Edna.Bindings.User\Edna.Bindings.User.csproj : error NU1101: Unable to find package System.IdentityModel.Tokens.Jwt. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [C:\Learn-lti\L
earn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj : error NU1101: Unable to find package System.IdentityModel.Tokens.Jwt. No packages exist with this id in source(s): Microsoft
 Visual Studio Offline Packages
  Failed to restore C:\Learn-lti\Learn-LTI\backend\Utils\Edna.Utils.Http\Edna.Utils.Http\Edna.Utils.Http.csproj (in 94 ms).
  Failed to restore C:\Learn-lti\Learn-LTI\backend\Bindings\Edna.Bindings.User\Edna.Bindings.User.csproj (in 94 ms).
  Failed to restore C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj (in 94 ms).
  Failed to restore C:\Learn-lti\Learn-LTI\backend\Utils\Edna.Utils.Linq\Edna.Utils.Linq\Edna.Utils.Linq.csproj (in 94 ms).
Errors while building Function App [ AssignmentLearnContent ]
At C:\Learn-lti\Learn-LTI\deployment\Install-Backend.ps1:61 char:9
+         throw "Errors while building Function App [ $FunctionName ]"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Errors while bu...tLearnContent ]:String) [], RuntimeException
    + FullyQualifiedErrorId : Errors while building Function App [ AssignmentLearnContent ]
 

PS C:\Learn-lti\Learn-LTI\deployment>

**Comment by renaldo-b** [comment]
> Running into problems when deploy.ps1 reaches step #10. See the error output on the end.
> 
> Following is present on the system.
> AZ CLI
> Microsoft .NET Core SDK 3.1.413 (x64)
> Microsoft .NET SDK 5.0.302 )x64)
> Node.js 14.17.6
> Powershell 5.1.22000.1
> Git 2.33
> 
> # Error:
> # STEP #10 - Installing the backend
> PS C:\Code> TerminatingError(): "Errors while building Function App [ AssignmentLearnContent ]"
> PS C:\Code> TerminatingError(): "Errors while building Function App [ AssignmentLearnContent ]"
> 
> I then tried to run publish.ps1. See all output from publish.ps1.
> 
> PS C:\Learn-lti\Learn-LTI\deployment> C:\Learn-lti\Learn-LTI\deployment\Publish.ps1
> cmdlet Publish.ps1 at command pipeline position 1
> Supply values for the following parameters:
> ResourceGroupName: MSLearnLTI
> AppName: MS-Learn-Lti-Tool-App
> 
> # =============================================================
> Gathering Deployment Info
> [ 23-9-2021 14:06:18 ] - [INFO] - Validating App Registration
> [ 23-9-2021 14:06:18 ] - [INFO] - Validating Resource Group
> [ 23-9-2021 14:06:19 ] - [INFO] - Getting Function Apps Info
> [ 23-9-2021 14:06:20 ] - [INFO] - Getting Static Website Info
> 
> # =============================================================
> Deployment Info Gathered
> # =============================================================
> Installing the backend
> [ 23-9-2021 14:06:21 ] - [INFO] - Switching to [../backend] as working directory
> [ 23-9-2021 14:06:21 ] - [INFO] - Installing FunctionApp -- AssignmentLearnContent
> [ 23-9-2021 14:06:21 ] - [INFO] - Publishing Project [ Edna.AssignmentLearnContent.csproj ] as FunctionApp
> [ 23-9-2021 14:06:21 ] - [INFO] - Building [ C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent ] --> [ Artifacts\AssignmentLearnContent ]
> [ 23-9-2021 14:06:22 ] - [INFO] - Determining projects to restore...
> C:\Learn-lti\Learn-LTI\backend\Utils\Edna.Utils.Linq\Edna.Utils.Linq\Edna.Utils.Linq.csproj : error NU1102: Unable to find package NETStandard.Library with version (>= 2.0.3) [C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.Assignme
> ntLearnContent\Edna.AssignmentLearnContent.csproj]
> C:\Learn-lti\Learn-LTI\backend\Utils\Edna.Utils.Linq\Edna.Utils.Linq\Edna.Utils.Linq.csproj : error NU1102: - Found 1 version(s) in Microsoft Visual Studio Offline Packages [ Nearest version: 1.6.0 ] [C:\Learn-lti\Learn-LTI\backend\Functions\Edna.Assignmen
> tLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
> C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj : error NU1101: Unable to find package AutoMapper.Extensions.Microsoft.DependencyInjection. No packages exist with this id in
> source(s): Microsoft Visual Studio Offline Packages
> C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj : error NU1101: Unable to find package Microsoft.Azure.Functions.Extensions. No packages exist with this id in source(s): Micr
> osoft Visual Studio Offline Packages
> C:\Learn-lti\Learn-LTI\backend\Utils\Edna.Utils.Http\Edna.Utils.Http\Edna.Utils.Http.csproj : error NU1102: Unable to find package NETStandard.Library with version (>= 2.0.3) [C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.Assignme
> ntLearnContent\Edna.AssignmentLearnContent.csproj]
> C:\Learn-lti\Learn-LTI\backend\Utils\Edna.Utils.Http\Edna.Utils.Http\Edna.Utils.Http.csproj : error NU1102: - Found 1 version(s) in Microsoft Visual Studio Offline Packages [ Nearest version: 1.6.0 ] [C:\Learn-lti\Learn-LTI\backend\Functions\Edna.Assignmen
> tLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
> C:\Learn-lti\Learn-LTI\backend\Bindings\Edna.Bindings.User\Edna.Bindings.User.csproj : error NU1102: Unable to find package NETStandard.Library with version (>= 2.0.3) [C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearn
> Content\Edna.AssignmentLearnContent.csproj]
> C:\Learn-lti\Learn-LTI\backend\Bindings\Edna.Bindings.User\Edna.Bindings.User.csproj : error NU1102: - Found 1 version(s) in Microsoft Visual Studio Offline Packages [ Nearest version: 1.6.0 ] [C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnC
> ontent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
> C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj : error NU1101: Unable to find package Microsoft.Azure.WebJobs.Extensions.Storage. No packages exist with this id in source(s)
> : Microsoft Visual Studio Offline Packages
> C:\Learn-lti\Learn-LTI\backend\Utils\Edna.Utils.Http\Edna.Utils.Http\Edna.Utils.Http.csproj : error NU1101: Unable to find package Microsoft.AspNetCore.Http.Features. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [C:\L
> earn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
> C:\Learn-lti\Learn-LTI\backend\Bindings\Edna.Bindings.User\Edna.Bindings.User.csproj : error NU1101: Unable to find package Microsoft.Azure.WebJobs.Extensions.Http. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [C:\Lea
> rn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
> C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj : error NU1101: Unable to find package Microsoft.Extensions.Http. No packages exist with this id in source(s): Microsoft Visua
> l Studio Offline Packages
> C:\Learn-lti\Learn-LTI\backend\Utils\Edna.Utils.Http\Edna.Utils.Http\Edna.Utils.Http.csproj : error NU1101: Unable to find package Microsoft.Azure.Services.AppAuthentication. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packag
> es [C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
> C:\Learn-lti\Learn-LTI\backend\Bindings\Edna.Bindings.User\Edna.Bindings.User.csproj : error NU1101: Unable to find package Microsoft.Extensions.Http. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [C:\Learn-lti\Learn-L
> TI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
> C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj : error NU1101: Unable to find package Microsoft.NET.Sdk.Functions. No packages exist with this id in source(s): Microsoft Vis
> ual Studio Offline Packages
> C:\Learn-lti\Learn-LTI\backend\Utils\Edna.Utils.Http\Edna.Utils.Http\Edna.Utils.Http.csproj : error NU1101: Unable to find package Microsoft.Extensions.DependencyInjection. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
> [C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
> C:\Learn-lti\Learn-LTI\backend\Bindings\Edna.Bindings.User\Edna.Bindings.User.csproj : error NU1101: Unable to find package Microsoft.AspNetCore.Http.Features. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [C:\Learn-lt
> i\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
> C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj : error NU1101: Unable to find package Microsoft.Azure.WebJobs.Extensions.Http. No packages exist with this id in source(s): M
> icrosoft Visual Studio Offline Packages
> C:\Learn-lti\Learn-LTI\backend\Utils\Edna.Utils.Http\Edna.Utils.Http\Edna.Utils.Http.csproj : error NU1101: Unable to find package Microsoft.Extensions.Http. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [C:\Learn-lti
> Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
> C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj : error NU1101: Unable to find package Microsoft.AspNetCore.Http.Features. No packages exist with this id in source(s): Micros
> oft Visual Studio Offline Packages
> C:\Learn-lti\Learn-LTI\backend\Bindings\Edna.Bindings.User\Edna.Bindings.User.csproj : error NU1101: Unable to find package Microsoft.Azure.Services.AppAuthentication. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [C:
> Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
> C:\Learn-lti\Learn-LTI\backend\Utils\Edna.Utils.Http\Edna.Utils.Http\Edna.Utils.Http.csproj : error NU1101: Unable to find package Microsoft.Extensions.Logging.Abstractions. No packages exist with this id in source(s): Microsoft Visual Studio Offline Package
> s [C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
> C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj : error NU1101: Unable to find package Microsoft.Azure.Services.AppAuthentication. No packages exist with this id in source(s)
> : Microsoft Visual Studio Offline Packages
> C:\Learn-lti\Learn-LTI\backend\Bindings\Edna.Bindings.User\Edna.Bindings.User.csproj : error NU1101: Unable to find package Microsoft.Extensions.DependencyInjection. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [C:\Le
> arn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
> C:\Learn-lti\Learn-LTI\backend\Utils\Edna.Utils.Http\Edna.Utils.Http\Edna.Utils.Http.csproj : error NU1101: Unable to find package System.IdentityModel.Tokens.Jwt. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [C:\Lear
> n-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
> C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj : error NU1101: Unable to find package Microsoft.Extensions.DependencyInjection. No packages exist with this id in source(s):
> Microsoft Visual Studio Offline Packages
> C:\Learn-lti\Learn-LTI\backend\Bindings\Edna.Bindings.User\Edna.Bindings.User.csproj : error NU1101: Unable to find package Microsoft.Extensions.Logging.Abstractions. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [C:\L
> earn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
> C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj : error NU1101: Unable to find package Microsoft.Extensions.Logging.Abstractions. No packages exist with this id in source(s):
> Microsoft Visual Studio Offline Packages
> C:\Learn-lti\Learn-LTI\backend\Bindings\Edna.Bindings.User\Edna.Bindings.User.csproj : error NU1101: Unable to find package System.IdentityModel.Tokens.Jwt. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [C:\Learn-lti\L
> earn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
> C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj : error NU1101: Unable to find package System.IdentityModel.Tokens.Jwt. No packages exist with this id in source(s): Microsoft
> Visual Studio Offline Packages
> Failed to restore C:\Learn-lti\Learn-LTI\backend\Utils\Edna.Utils.Http\Edna.Utils.Http\Edna.Utils.Http.csproj (in 94 ms).
> Failed to restore C:\Learn-lti\Learn-LTI\backend\Bindings\Edna.Bindings.User\Edna.Bindings.User.csproj (in 94 ms).
> Failed to restore C:\Learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj (in 94 ms).
> Failed to restore C:\Learn-lti\Learn-LTI\backend\Utils\Edna.Utils.Linq\Edna.Utils.Linq\Edna.Utils.Linq.csproj (in 94 ms).
> Errors while building Function App [ AssignmentLearnContent ]
> At C:\Learn-lti\Learn-LTI\deployment\Install-Backend.ps1:61 char:9
> 
> * ```
>       throw "Errors while building Function App [ $FunctionName ]"
>   ```
> * ```
>       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   
>   * CategoryInfo          : OperationStopped: (Errors while bu...tLearnContent ]:String) [], RuntimeException
>   * FullyQualifiedErrorId : Errors while building Function App [ AssignmentLearnContent ]
> 
> PS C:\Learn-lti\Learn-LTI\deployment>

**Comment by leestott** [comment]
@renaldo-b so the error looks like your missing
Unable to find package Microsoft.Azure.WebJobs.Extensions.Storage. No packages exist with this id in source(s)
: Microsoft Visual Studio Offline Packages
: Unable to find package NETStandard.Library with version (>= 2.0.3)
 
 So it looks like your missing nuget libraries from your install 
 
.Net Standard Libraries https://www.nuget.org/packages/NETStandard.Library/ 
Also it looks like your machine doesn't have any Visual Studio tools installed?

If you have Visual Studio Installed on your deployment machine 

You could go to Tools -> Options -> NuGet Package Manager -> Package Sources then add a new source link like screenshot below.
![image](https://user-images.githubusercontent.com/2511341/134580240-87186a12-527b-424c-857c-fb420c00485f.png)

BTW, NuGet Package Manager are automatically installed with any .NET-related workloads in VS 2019.

**Comment by leestott** [comment]
@renaldo-b did you reboot your machine also after installing the prerequisites? We have seen these error also if you have NOT rebooted

**Comment by renaldo-b** [comment]
@leestott Forgot to mention, but yes I did reboot my machine several times after the installation.

**Comment by renaldo-b** [comment]
Problem solved! The missing NuGet Package Manager was the issue. After importing the package the app created successfully.

**Comment by leestott** [comment]
Thanks for the update, glad this was easily sorted.
