### ISSUE TITLE
Unable to register for Organization Reporting from B2C tenant

### ISSUE THREAD

**Issue by robhutchison** [microsoft/Learn-LTI#164]
I have an Azure B2C tenant setup which is serving Moodle and the LTI application. I have those working fine but I now need to be able to fetch the learner progress data which appears to be only available via a data share invitation.

**What I have tried so far**

I have used Azure Lighthouse to provide access to a resource group housing the data share in our main tenant as I could not create it in the B2C tenant.  I access the organization reporting setup page with a user that is local to the B2C tenant and is part of a security group which has permissions to access the resource group.  This allows the values to be populated on the form so that the Accept button becomes available.

However, when I click accept I get the error **"Failed to create Share Subscription 'learningdata' : This operation is not allowed outside your home tenant unless you register your email."**
I have been to https://docs.microsoft.com/en-us/rest/api/datashare/2019-11-01/email-registrations/register-email which shows the activation request as pending though it shows the email as onmicrosoft.com even if I set an email for the user.
 
I have tried again with a user which has already validated their email for the B2C tenant (with a gmail account so it didn't get tied to another azure tenant) using https://docs.microsoft.com/en-us/rest/api/datashare/2019-11-01/email-registrations/activate-email but this just gives 
<img width="469" alt="org reporting for user with gmail account" src="https://user-images.githubusercontent.com/82097253/139826532-e1461b48-015d-40d1-aa10-1f27eae7c3ed.png">

**Expected behavior**
I should be able to accept the invitation and then proceed to setup the data share to receive the progress data.

**LMS:**
 - Platform: Moodle
 - Version 3.11
 - Installation: Bitnami Moodle on Azure VM

**Comment by leestott** [comment]
Hi @robhutchison

For Learn Organisational Reporting 

You need to see https://docs.microsoft.com/learn/support/org-reporting

For support on Learn Organisational Reporting please email learnfororg@microsoft.com
