### ISSUE TITLE
Unable to install Lit system normally

### ISSUE THREAD

**Issue by a00110110** [microsoft/Learn-LTI#167]
I tried to install LTI several times and still failed

[error.pptx](https://github.com/microsoft/Learn-LTI/files/7839326/error.pptx)
[Desktop.zip](https://github.com/microsoft/Learn-LTI/files/7839335/Desktop.zip)
1. The version of my moodle system is 3.11.4+
2. I use Azure AD and created multiple user accounts
3. I use Admin in Moodle to create a course first, then use another browser, log in with a teacher account, and use the teacher account to link to LTI courses

The attachment is a screenshot of the related fault message, which I put in the PPT
And F12 to view the trace and stack LOG file. Please refer to it

thank you

**Comment by leestott** [comment]
Hi @a00110110 so please follow the troubleshooting guide https://github.com/microsoft/Learn-LTI/blob/main/docs/TROUBLESHOOTING.md 

Debugging Errors related to http500 indicated in Browser with Oops! Something went wrong.. 

We suggest you go to our help page https://github.com/microsoft/Learn-LTI/blob/main/docs/TROUBLESHOOTING.md 

This results in you being unable to open the Assignments page in Learn-LTI. Users access failing with http500 which essentially has been the source of the Oops! Something went wrong error message in the browser window.

Please see browser logs  so press F12 and reopen the page to follow the stack trace if indicate that the membership call being sent to the LMS (Moodle) to ensure the users are validating of this is returning a 401 Unauthorized and the Learn LTI tool in unable to get the course members from the LMS and hence the it is giving a 500 response.

This results in you being unable to open the Assignments page in Learn-LTI. Users access failing with http500 which essentially has been the source of the Oops! Something went wrong error message in the browser window.

Also Please make sure that while configuring the tool in Moodle, Under Services, IMS LTI Names and Role Provisioning: Use this service to retrieve members’ information as per privacy settings. is selected as mentioned in the Configuration Guide Learn
https://github.com/microsoft/Learn-LTI/blob/main/images/Config.8.png

**Comment by a00110110** [comment]
Why can't I find "Azure subscription" when I installed LTI?

For fault messages, please refer to the cloud space, 20220118_0636 folder
http://gg.gg/xkxdq

**Comment by leestott** [comment]
Hi I see you managed to get the services deployed successfully re https://github.com/microsoft/Learn-LTI/issues/170 so I will close this issues
