### ISSUE TITLE
Throttling issue running the script

### ISSUE THREAD

**Issue by ayameeno** [microsoft/Learn-LTI#181]
Was anyone able to run the deployment script? It seems the script tries to create huge amount of resources that causes throttling restriction on Azure. I keep getting 429 Too many requests and it fails

The script then times out.

Is there a way we can break the deployment script so it doesnt cause this issue? Raised a ticket with Microsoft to increase the throttling limit but it doesn't seem they allow that.

Kinda stuck in this - following the guidelines on Microsoft and then getting stuck on Microsoft azure

Anyone was able to deploy it?

**Comment by leestott** [comment]
@ayameeno do you have any more details of the issue your having we have not seen this issue before.

**Comment by leestott** [comment]
No response on issue and this has not been reported by other user if this issue persists, please reopen the issue
