### ISSUE TITLE
Stuck on step #6

### ISSUE THREAD

**Issue by zozo1977** [microsoft/Learn-LTI#185]
# Bug
**Describe the bug**
We followed deployment documentation and installed all requirements. Application deployment script is stuck on step #6 for 24 hours and is not displaying any errors. 

**To Reproduce**
Deploy app following documentation.

**Expected behavior**
Application deployed.

**Screenshots**
![image](https://user-images.githubusercontent.com/49674270/166918086-c19b161f-9918-410c-b0bf-2835c0a425bf.png)

**LMS (please complete the following information):**
 - Platfrom: Moodle
 - 3.11
 - Installation Hosted on Linode Linux VM

**Desktop (please complete the following information):**
 - OS: Windows
 - Edge
 - Win 10 x64, Edge 101.0.1210.32 x64
 - 
**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by leestott** [comment]
Can you please ensure you have the prerequisite installed.

See: https://github.com/microsoft/Learn-LTI/blob/main/docs/DEPLOYMENT_GUIDE.md

To begin, you will need:

[Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest?WT.mc_id=learnlti-github-cxa)
[DotNet Core SDK .NET Core 3.1](https://dotnet.microsoft.com/download/dotnet/3.1?WT.mc_id=learnlti-github-cxa)
[Node.js](https://nodejs.org/en/download/)
[Powershell](https://docs.microsoft.com/powershell/scripting/install/installing-powershell?view=powershell-7?WT.mc_id=learnlti-github-cxa)
[Git](https://git-scm.com/downloads)
An Azure subscription
Note: Please ensure you reboot your machine after the installation of the Prerequisities
