### ISSUE TITLE
Bug - can't redeploy due to key vault persisting

### ISSUE THREAD

**Issue by danielmusselwhite** [microsoft/Learn-LTI#187]
# Bug
On Microsoft CLI 2.34.0, the deploy script for Learn-LTI fails on Step 6 with the following error:

"""
ERROR: {"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"NotFound","message":"{

  "error": {

    "code": "ParentResourceNotFound",

    "message": "Can not perform requested operation on nested resource. Parent resource 'kv-6i5ioyg4m' not found."

  }

}"},{"code":"Conflict","message":"{

  "Code": "Conflict",

  "Message": "Server Farm with name 'learncontent-6i5ioyg4m' already exists for subscription 'd860254d-e172-4286-9161-681edd01201a'.",

  "Target": null,

  "Details": [

    {

      "Message": "Server Farm with name 'learncontent-6i5ioyg4m' already exists for subscription 'd860254d-e172-4286-9161-681edd01201a'."

    },

    {

      "Code": "Conflict"

    },

    {

      "ErrorEntity": {

        "ExtendedCode": "03015",

        "MessageTemplate": "Server Farm with name '{0}' already exists for subscription '{1}'.",

        "Parameters": [

          "learncontent-6i5ioyg4m",

          "d860254d-e172-4286-9161-681edd01201a"

        ],

        "Code": "Conflict",

        "Message": "Server Farm with name 'learncontent-6i5ioyg4m' already exists for subscription 'd860254d-e172-4286-9161-681edd01201a'."

      }

    }

  ],

  "Innererror": null

}"},{"code":"Conflict","message":"{

  "error": {

    "code": "VaultAlreadyExists",

    "message": "The vault name 'kv-6i5ioyg4m' is already in use. Vault names are globaly unique so it is possible that the name is already taken. If you are sure that the vault name was not taken then it is possible that a vault with the same name was recently deleted but not purged after being placed in a recoverable state. If the vault is in a recoverable state then the vault will need to be purged before reusing the name. For more information on soft delete and purging a vault follow this link https://go.microsoft.com/fwlink/?linkid=2147740."

  }

}"}]}}
"""

It appears this is as a result of the azuredeploy.json having the keyvaults enableSoftDelete and enablePurgeProtection properties set to true by default. Meaning it succeeded on building the key vault on the first run; however, it failed on a later stage for an unrelated reason which we then fixed- and then when we attempt to clean-up and then re-deploy using the fix we encountered this issue due to the kv having persisted with us being unable to purge it.

**To Reproduce**
1. run deploy.bat
2. run clean.bat
3. rerun deploy.bat

**Expected behavior**
it should succeed in the deploy.bat in creating a new learn-lti resource group in azure

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave

**Comment by leestott** [comment]
@danielmusselwhite this is a documented issue 

SEE https://github.com/microsoft/Learn-LTI/blob/main/docs/TROUBLESHOOTING.md#purging-key-vaults 

Your Azure Key Vault may be set to soft delete enabled.

As such if you encounter an issue in the deployment you will have to delete your resource and deploy again you may be presented with this following error.

ERROR: Deployment failed. Correlation ID: ************-****-****-**********. {
  "error": {
    "code": "ParentResourceNotFound",
    "message": "Can not perform requested operation on nested resource. Parent resource 'kv-******' not found."

Due having soft delete enabled on the Key vault. The Key vault could not be recreated after the install initially fails. See more details on [Azure Key Vault recovery overview | Microsoft Docs](https://docs.microsoft.com/azure/key-vault/general/key-vault-recovery?tabs=azure-portal)

Key Vault Recovery features are designed to prevent the accidental or malicious deletion of your key vault and secrets, keys, and certificate stored inside key-vault. So under soft delete the key vault is still available for 90 days after deletion therefore you need to purge the deleted Key Vault before it can be recreated.

To purge a deleted Key vault
Go to key vaults-> manage deleted vault
Select the kv and select purge
See the following screenshot https://github.com/microsoft/Learn-LTI/blob/main/docs/TROUBLESHOOTING.md#purging-key-vaults

**Comment by aazswapnil** [comment]
We ran into same issue when we accidentally deployed in the wrong region. The Key Vault was deployed with purge protection in the wrong region. We could not move it, we could not purge it before the wait period. The workaround we used was to edit the substring values for the "uniqueIdentifier" variable in azuredeploy.json so that our new deployment uses a new unique-id, which creates a new Key Vault in the correct region.

**Comment by danielmusselwhite** [comment]
@aazswapnil 

Thank you; that workaround works for us too.
Have also disabled the soft delete and purge protection options so the issue doesn't persist in the future.

**Comment by warrenbuhler** [comment]
Re-opening this issue to specifically focus on the purge protection and how to handle that around deploys. 

We were able to work around it manually by changing the name the key vault was created with -- either by changing the resource name or by adding additional information into the call to create a unique string. 

For possible development changes, I see a several potential options. 

1st, prompt the user if they want to use purge protection when creating the key vault, strongly reccomend that they do unless they know this is a temporary install. If they decide not to, create the key vault without purge protection.

A disadvantage here is that some sites may choose not to use purge protection on their final version, which is a less secure choice. 

2nd, change the creation of the unique identifier in azuredeploy.json to include some randomness or a incrementer between runs. 
current: "uniqueIdentifier": "[substring(uniqueString(subscription().subscriptionId, resourceGroup().id),0,9)]",
proposed: "uniqueIdentifier": "[substring(uniqueString(subscription().subscriptionId, resourceGroup().id, randomOrIncrement()),0,9)]",

This could also be changed in the item for keyVaultName directly:
"keyVaultName": "[toLower(concat('kv', variables('ProjectNameSuffix')))]",
-- ProjectNameSuffix uses "uniqueIdentifier" 

One disadvantage here is that any scripts you made relying on the unique identifier's output would need to be updated. 

3rd, I'm not sure how feasible it is. But potentially we could try to recover a soft deleted key vault as deploy if the creation fails. Then we could re-use the old object. This could leave old secrets still available which is likely non-intuitive behaviour. 

4th, enable purge protection of the key vault only when all other configuration is complete. At this point we are reasonably sure the LTI setup is complete and correct and the likelihood of needing to immediately re-deploy is low. This however will not help with future re-deploys later. 

Options 1 and 4 are likely very fast do not address the situation of handling the purge protected key vault if you have one. Option 1 also is more likely to leave sites in a less secure configuration unless they choose to update it later.

Option 2 is likely faster and still very straightforward but does change the key vault name in use which might be disruptive for admin scripts.

Option 3 has perhaps the least impact to the deployment process and potential maintenance for the admin but is not-intuitive behaviour and could lead to old secrets staying available. It is also the most complicated option. 

I reccomend option 2 as there is likely an expectation that you have to modify the admin scripts around a redeploy. It is also relatively straightforward to do compared to option 3.

**Comment by leestott** [comment]
Issue closed as troubleshooting guide has been updated to reflect this https://user-images.githubusercontent.com/2511341/134580240-87186a12-527b-424c-857c-fb420c00485f.png
