### ISSUE TITLE
Deploying Microsoft Learn LTI error step 6

### ISSUE THREAD

**Issue by phergo23** [microsoft/Learn-LTI#189]
Hi I am trying to deploy Microsoft Learn LTI but after run run.bat it stops with a error on step 6. This is what it say:
 
      ______          _____  _   _            _   _______ _____
| |    |  ____|   /\   |  __ \| \ | |          | | |__   __|_   _|
| |    | |__     /  \  | |__) |  \| |  ______  | |    | |    | |
| |    |  __|   / /\ \ |  _  /| . ` | |______| | |    | |    | |
| |____| |____ / ____ \| | \ \| |\  |          | |____| |   _| |_
|______|______/_/    \_\_|  \_\_| \_|          |______|_|  |_____|

La transcripción ha comenzado. El archivo de salida es C:\Learn-LTI-main\deployment\Log\Transcript-03-06-2022-09-22-41.log

=============================================================
STEP #1 - Logging into Azure
=============================================================

WARNING: A web browser has been opened at https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.

=============================================================
STEP #2 - Choose Subscription
=============================================================

=============================================================
STEP #3 - Choose Location
(Please refer to the Documentation / ReadMe on Github for the List of Supported Locations)
=============================================================

Name
-------------------
eastus
eastus2
southcentralus
westus2
westus3
australiaeast
southeastasia
northeurope
swedencentral
uksouth
westeurope
centralus
southafricanorth
centralindia
eastasia
japaneast
koreacentral
canadacentral
francecentral
germanywestcentral
norwayeast
switzerlandnorth
brazilsouth
eastus2euap
centralusstage
eastusstage
eastus2stage
northcentralusstage
southcentralusstage
westusstage
westus2stage
asia
asiapacific
australia
brazil
canada
europe
france
germany
global
india
japan
korea
norway
southafrica
switzerland
uae
uk
unitedstates
unitedstateseuap
eastasiastage
southeastasiastage
northcentralus
westus
jioindiawest
uaenorth
centraluseuap
westcentralus
southafricawest
australiacentral
australiacentral2
australiasoutheast
japanwest
jioindiacentral
koreasouth
southindia
westindia
canadaeast
francesouth
germanynorth
norwaywest
switzerlandwest
ukwest
uaecentral
brazilsoutheast

Enter Location From Above List for Resource Provisioning: eastus

=============================================================
STEP #4 - Registering Azure Active Directory App
=============================================================

WARNING: This command or command group has been migrated to Microsoft Graph API. Please carefully review all breaking changes introduced during this migration: https://docs.microsoft.com/cli/azure/microsoft-graph-migration
WARNING: This command or command group has been migrated to Microsoft Graph API. Please carefully review all breaking changes introduced during this migration: https://docs.microsoft.com/cli/azure/microsoft-graph-migration
WARNING: This command or command group has been migrated to Microsoft Graph API. Please carefully review all breaking changes introduced during this migration: https://docs.microsoft.com/cli/azure/microsoft-graph-migration
WARNING: Invoking `az ad app permission grant --id 75de07ad-52fa-462a-841f-66fc0e60615d --api 00000003-0000-0000-c000-000000000000` is needed to make the change effective
App Created Successfully

=============================================================
STEP #5 - Creating Resource Group
=============================================================

Resource Group Created Successfully

=============================================================
STEP #6 - Creating Resources in Azure
=============================================================

WARNING: This command or command group has been migrated to Microsoft Graph API. Please carefully review all breaking changes introduced during this migration: https://docs.microsoft.com/cli/azure/microsoft-graph-migration
ERROR: {"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"NotFound","message":"{\r\n  \"error\": {\r\n    \"code\": \"ParentResourceNotFound\",\r\n    \"message\": \"Can not perform requested operation on nested resource. Parent resource 'kv-ijgib2l3s' not found.\"\r\n  }\r\n}"},{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"BadRequest\",\r\n    \"message\": \"Invalid value found at accessPolicies[0].ObjectId: \"\r\n  }\r\n}"}]}}
La transcripción se ha detenido. El archivo de salida es C:\Learn-LTI-main\deployment\Log\Transcript-03-06-2022-09-22-41.log
Press any Key to Exit:

**Comment by leestott** [comment]
@phergo23 this is a known issue see https://github.com/microsoft/Learn-LTI/issues/186 there is a temp workaround in this issue.

**Comment by leestott** [comment]
@phergo23  
Please simply downgrade your Azure CLI to v2.27

**Comment by phergo23** [comment]
Thank you for the response, a downgrade to 2.27.0 but now I have two problems. 
the first one is that I get this error on step 10

STEP #10 - Installing the backend
=============================================================
PS>ErrorTerminación(): "Errors while building Function App [ AssignmentLearnContent ]"
PS>ErrorTerminación(): "Errors while building Function App [ AssignmentLearnContent ]"
**********************
Fin de la transcripción de Windows PowerShell
Hora de finalización: 20220607090657
**********************

And the second is that I try to rerun by first run clean and then try to purge the key-vault but it has soft delete and purge protection so I can not delete the key vault and I find on all places that if it is enable it can not be disable so I get error on step 6

=============================================================
STEP #6 - Creating Resources in Azure
=============================================================


ERROR: {"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"NotFound","message":"{\r\n  \"error\": {\r\n    \"code\": \"ParentResourceNotFound\",\r\n    \"message\": \"Can not perform requested operation on nested resource. Parent resource 'kv-ijgib2l3s' not found.\"\r\n  }\r\n}"},{"code":"Conflict","message":"{\r\n  \"error\": {\r\n    \"code\": \"VaultAlreadyExists\",\r\n    \"message\": \"The vault name 'kv-ijgib2l3s' is already in use. Vault names are globaly unique so it is possible that the name is already taken. If you are sure that the vault name was not taken then it is possible that a vault with the same name was recently deleted but not purged after being placed in a recoverable state. If the vault is in a recoverable state then the vault will need to be purged before reusing the name. For more information on soft delete and purging a vault follow this link https://go.microsoft.com/fwlink/?linkid=2147740.\"\r\n  }\r\n}"}]}}

**Comment by phergo23** [comment]
I solve the two issues, first issue I change the the value "keyVaultName" to be from kv to ky on deploy.ps1 file, so the error that keyvault already exist was solved, and the second error I solve it installing  ASP.NET Core Runtime 3.0.0 beacause I install 3.1 it appears to be this specific version. Also I get a error on step 12 but this was solve by re-running run.bat

**Comment by leestott** [comment]
@phergo23  so you should run the cleanup script after a failed installation and purge your keyvault https://github.com/microsoft/Learn-LTI/blob/main/docs/TROUBLESHOOTING.md#purging-key-vaults this is in the troubleshooting guide https://github.com/microsoft/Learn-LTI/blob/main/docs/TROUBLESHOOTING.md

Can you confirm you have successfully installed the solution.

**Comment by phergo23** [comment]
I can not purge the keyvault because when it was created if create with soft delete enable and with purge protection enable, this parameters can not be change once it was enable so I receive an error when I try to purge it.

**Comment by leestott** [comment]
Yes see https://docs.microsoft.com/en-gb/azure/key-vault/general/key-vault-recovery?tabs=azure-portal

Which refers you to instructions at https://docs.microsoft.com/en-gb/azure/key-vault/general/key-vault-recovery?tabs=azure-portal 

Follow these instructions 
https://docs.microsoft.com/en-gb/azure/key-vault/general/key-vault-recovery?tabs=azure-portal

**Comment by leestott** [comment]
@phergo23 please see https://github.com/microsoft/Learn-LTI/issues/187 this has a workaround

**Comment by phergo23** [comment]
thank you for the response I use a workaround similar to this mentioned , I change the the value "keyVaultName" to be from kv to ky on deploy.ps1 file so thescritp run without problems.

**Comment by leestott** [comment]
Thanks for the confirmation we have had the troubleshooting guide updated to reflect this.
