### ISSUE TITLE
LTI 1.3 on Open edX Lilac

### ISSUE THREAD

**Issue by rainbowrytsar** [microsoft/Learn-LTI#195]
Hello,

We are trying to set up the LTI-consumer in our courses on Lilac.
We are using  LTI 1.3.
Microsoft Learn LTI Tool is deployed and is set up, but there is no setting tab in the lti-consumer unit. Instead we get 'The assignment is not yet published'.
![image](https://user-images.githubusercontent.com/15081715/176640277-7f91bf3f-81fd-41fe-a863-11e83d7b9551.png)

Thank you in advance!

**Comment by leestott** [comment]
@rainbowrytsar please follow the configuration guide at https://github.com/microsoft/Learn-LTI/blob/main/docs/CONFIGURATION_GUIDE.md#Open-edX-LMS to debug your solution.

**Comment by leestott** [comment]
@rainbowrytsar did you try logging in a teacher to first create the course. The account which you initially have to log in a teacher permission on OpenEdx as your first task is configure the course. see https://github.com/microsoft/Learn-LTI/blob/main/docs/USER_GUIDE.md

From the error it looks like you have logged in with a valid student account but as there has been no course created - you receive this message.

**Comment by rainbowrytsar** [comment]
@leestott Thank you for your reply. This message was shown to the course admin before the course has been set up. I managed to solve the problem by using the same email for both course administration and azure tool management. I had to be logged in to Azure Portal prior to that. Thank you again for your engagement!
