### ISSUE TITLE
Enhancement - Deploy script should check and report on prerequisites (ie Azure Command Line)

### ISSUE THREAD

**Issue by warrenbuhler** [microsoft/Learn-LTI#196]
**Is your feature request related to a problem? Please describe.**
There are several requirements for the deploy script to run properly and to completion. They are documented and the failure conditions are mostly, if not all represented in the troubleshooting guide. However, it is common for people to miss a requirement or assume they have it installed. Then after the deploy script fails, they have to troubleshoot and run cleanup

**Describe the solution you'd like**
The deploy script should check for each prerequisite before starting to run and then report on any that are missing. It should not progress to the point of deploying unless everything required is installed. 

**Describe alternatives you've considered**
You could have the deploy script prompt to install missing dependencies, but that is likely far more complicated and not worthwhile. 

**Additional context**
NA

**Comment by leestott** [comment]
This is a lovely idea and will prevent lots of the installation problems we would welcome this PR

**Comment by leestott** [comment]
Fixed with https://github.com/microsoft/Learn-LTI/pull/209
