### ISSUE TITLE
Deploy.ps1 stops on step 6

### ISSUE THREAD

**Issue by renaldo-b** [microsoft/Learn-LTI#197]
I want to run the run.bat file for the setup of the LTI. After step 6 of the deploy.ps1 script I get an error. See the log files attached.

My account has the following roles:
AAD: Global Administrator
Azure subscription: Contributor at the subscription level.

Both roles are behind a active Azure Priviledged Management (PIM) assignment. So the assignment is still active when executing the script. There is no active Powershell session present. Beforehand I ran the clear-azcontext commandlet.

I have all the prerequisites, what am I missing here?

Thanks in advance

[Log-12-07-2022-15-03-38.log](https://github.com/microsoft/Learn-LTI/files/9093372/Log-12-07-2022-15-03-38.log)
[Transcript-12-07-2022-15-03-38.log](https://github.com/microsoft/Learn-LTI/files/9093373/Transcript-12-07-2022-15-03-38.log)

**Comment by leestott** [comment]
@renaldo-b please see https://github.com/microsoft/Learn-LTI/issues/189

Known issues CLI version
Run the cleanup script 
Ensure your keyvault is purged and keyvault name changes 
See the troubleshooting guide

**Comment by renaldo-b** [comment]
Thanks, I got it working with downgrading to AZ CLI 2.27.0.

Now at Step 10 I got the following:

```
=============================================================
STEP #10 - Installing the backend
=============================================================
PS C:\learn-lti\Learn-LTI\deployment> TerminatingError(): "Errors while building Function App [ AssignmentLearnContent ]"
PS C:\learn-lti\Learn-LTI\deployment> TerminatingError(): "Errors while building Function App [ AssignmentLearnContent ]"
```

The Logfile has some resolving issues:

``[ 18/07/2022 15:48:19 ] - [INFO] - Building [ C:\learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent ] --> [ Artifacts\AssignmentLearnContent ]
[ 18/07/2022 15:48:23 ] - [INFO] -   Determining projects to restore...
C:\learn-lti\Learn-LTI\backend\Utils\Edna.Utils.Linq\Edna.Utils.Linq\Edna.Utils.Linq.csproj : error NU1100: Unable to resolve 'NETStandard.Library (>= 2.0.3)' for '.NETStandard,Version=v2.0'. [C:\learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
C:\learn-lti\Learn-LTI\backend\Bindings\Edna.Bindings.User\Edna.Bindings.User.csproj : error NU1100: Unable to resolve 'NETStandard.Library (>= 2.0.3)' for '.NETStandard,Version=v2.0'. [C:\learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
C:\learn-lti\Learn-LTI\backend\Utils\Edna.Utils.Http\Edna.Utils.Http\Edna.Utils.Http.csproj : error NU1100: Unable to resolve 'NETStandard.Library (>= 2.0.3)' for '.NETStandard,Version=v2.0'. [C:\learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
C:\learn-lti\Learn-LTI\backend\Bindings\Edna.Bindings.User\Edna.Bindings.User.csproj : error NU1100: Unable to resolve 'Microsoft.Azure.WebJobs.Extensions.Http (>= 3.0.2)' for '.NETStandard,Version=v2.0'. [C:\learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
C:\learn-lti\Learn-LTI\backend\Bindings\Edna.Bindings.User\Edna.Bindings.User.csproj : error NU1100: Unable to resolve 'Microsoft.Extensions.Http (>= 3.1.4)' for '.NETStandard,Version=v2.0'. [C:\learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
C:\learn-lti\Learn-LTI\backend\Bindings\Edna.Bindings.User\Edna.Bindings.User.csproj : error NU1100: Unable to resolve 'Microsoft.AspNetCore.Http.Features (>= 3.1.5)' for '.NETStandard,Version=v2.0'. [C:\learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
C:\learn-lti\Learn-LTI\backend\Bindings\Edna.Bindings.User\Edna.Bindings.User.csproj : error NU1100: Unable to resolve 'Microsoft.Azure.Services.AppAuthentication (>= 1.4.0)' for '.NETStandard,Version=v2.0'. [C:\learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
C:\learn-lti\Learn-LTI\backend\Bindings\Edna.Bindings.User\Edna.Bindings.User.csproj : error NU1100: Unable to resolve 'Microsoft.Extensions.DependencyInjection (>= 3.1.9)' for '.NETStandard,Version=v2.0'. [C:\learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
C:\learn-lti\Learn-LTI\backend\Bindings\Edna.Bindings.User\Edna.Bindings.User.csproj : error NU1100: Unable to resolve 'Microsoft.Extensions.Logging.Abstractions (>= 3.1.5)' for '.NETStandard,Version=v2.0'. [C:\learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
C:\learn-lti\Learn-LTI\backend\Bindings\Edna.Bindings.User\Edna.Bindings.User.csproj : error NU1100: Unable to resolve 'System.IdentityModel.Tokens.Jwt (>= 6.6.0)' for '.NETStandard,Version=v2.0'. [C:\learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
C:\learn-lti\Learn-LTI\backend\Utils\Edna.Utils.Http\Edna.Utils.Http\Edna.Utils.Http.csproj : error NU1100: Unable to resolve 'Microsoft.AspNetCore.Http.Features (>= 3.1.5)' for '.NETStandard,Version=v2.0'. [C:\learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
C:\learn-lti\Learn-LTI\backend\Utils\Edna.Utils.Http\Edna.Utils.Http\Edna.Utils.Http.csproj : error NU1100: Unable to resolve 'Microsoft.Azure.Services.AppAuthentication (>= 1.4.0)' for '.NETStandard,Version=v2.0'. [C:\learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
C:\learn-lti\Learn-LTI\backend\Utils\Edna.Utils.Http\Edna.Utils.Http\Edna.Utils.Http.csproj : error NU1100: Unable to resolve 'Microsoft.Extensions.DependencyInjection (>= 3.1.9)' for '.NETStandard,Version=v2.0'. [C:\learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
C:\learn-lti\Learn-LTI\backend\Utils\Edna.Utils.Http\Edna.Utils.Http\Edna.Utils.Http.csproj : error NU1100: Unable to resolve 'Microsoft.Extensions.Http (>= 3.1.3)' for '.NETStandard,Version=v2.0'. [C:\learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
C:\learn-lti\Learn-LTI\backend\Utils\Edna.Utils.Http\Edna.Utils.Http\Edna.Utils.Http.csproj : error NU1100: Unable to resolve 'Microsoft.Extensions.Logging.Abstractions (>= 3.1.5)' for '.NETStandard,Version=v2.0'. [C:\learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
C:\learn-lti\Learn-LTI\backend\Utils\Edna.Utils.Http\Edna.Utils.Http\Edna.Utils.Http.csproj : error NU1100: Unable to resolve 'System.IdentityModel.Tokens.Jwt (>= 6.6.0)' for '.NETStandard,Version=v2.0'. [C:\learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj]
C:\learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj : error NU1100: Unable to resolve 'AutoMapper.Extensions.Microsoft.DependencyInjection (>= 7.0.0)' for '.NETCoreApp,Version=v3.1'.
C:\learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj : error NU1100: Unable to resolve 'Microsoft.Azure.Functions.Extensions (>= 1.0.0)' for '.NETCoreApp,Version=v3.1'.
C:\learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj : error NU1100: Unable to resolve 'Microsoft.Azure.WebJobs.Extensions.Storage (>= 3.0.11)' for '.NETCoreApp,Version=v3.1'.
C:\learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj : error NU1100: Unable to resolve 'Microsoft.Extensions.Http (>= 3.1.4)' for '.NETCoreApp,Version=v3.1'.
C:\learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj : error NU1100: Unable to resolve 'Microsoft.NET.Sdk.Functions (>= 3.0.3)' for '.NETCoreApp,Version=v3.1'.
C:\learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj : error NU1100: Unable to resolve 'Microsoft.Azure.WebJobs.Extensions.Http (>= 3.0.2)' for '.NETCoreApp,Version=v3.1'.
C:\learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj : error NU1100: Unable to resolve 'Microsoft.AspNetCore.Http.Features (>= 3.1.5)' for '.NETCoreApp,Version=v3.1'.
C:\learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj : error NU1100: Unable to resolve 'Microsoft.Azure.Services.AppAuthentication (>= 1.4.0)' for '.NETCoreApp,Version=v3.1'.
C:\learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj : error NU1100: Unable to resolve 'Microsoft.Extensions.DependencyInjection (>= 3.1.9)' for '.NETCoreApp,Version=v3.1'.
C:\learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj : error NU1100: Unable to resolve 'Microsoft.Extensions.Logging.Abstractions (>= 3.1.5)' for '.NETCoreApp,Version=v3.1'.
C:\learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj : error NU1100: Unable to resolve 'System.IdentityModel.Tokens.Jwt (>= 6.6.0)' for '.NETCoreApp,Version=v3.1'.
C:\learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj : error NU1100: Unable to resolve 'Microsoft.NETCore.App.Ref (= 3.1.0)' for '.NETCoreApp,Version=v3.1'.
C:\learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj : error NU1100: Unable to resolve 'Microsoft.WindowsDesktop.App.Ref (= 3.1.0)' for '.NETCoreApp,Version=v3.1'.
C:\learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj : error NU1100: Unable to resolve 'Microsoft.AspNetCore.App.Ref (= 3.1.10)' for '.NETCoreApp,Version=v3.1'.
  Failed to restore C:\learn-lti\Learn-LTI\backend\Bindings\Edna.Bindings.User\Edna.Bindings.User.csproj (in 283 ms).
  Failed to restore C:\learn-lti\Learn-LTI\backend\Utils\Edna.Utils.Linq\Edna.Utils.Linq\Edna.Utils.Linq.csproj (in 283 ms).
  Failed to restore C:\learn-lti\Learn-LTI\backend\Utils\Edna.Utils.Http\Edna.Utils.Http\Edna.Utils.Http.csproj (in 283 ms).
  Failed to restore C:\learn-lti\Learn-LTI\backend\Functions\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent\Edna.AssignmentLearnContent.csproj (in 283 ms).
[ 18/07/2022 15:48:23 ] - [ERROR] - Exception.Message [ Errors while building Function App [ AssignmentLearnContent ] ]
[ 18/07/2022 15:48:23 ] - [ERROR] - Exception.Type    [ System.Management.Automation.RuntimeException ]
[ 18/07/2022 15:48:23 ] - [ERROR] - Error occurred while executing the Script. Please report the bug on Github (along with Error Message & Logs)
``

I have the .NET SDK 6.0.302(x64) om my pc if that's helpfull.

**Comment by leestott** [comment]
So you need to have Dot NET CORE SDK

[Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest?WT.mc_id=learnlti-github-cxa)
[DotNet Core SDK .NET Core 3.1](https://dotnet.microsoft.com/download/dotnet/3.1?WT.mc_id=learnlti-github-cxa)
[Node.js](https://nodejs.org/en/download/)
[Powershell](https://docs.microsoft.com/powershell/scripting/install/installing-powershell?view=powershell-7?WT.mc_id=learnlti-github-cxa)
[Git](https://git-scm.com/downloads)
An Azure subscription

Note: Please ensure you reboot your machine after the installation of the Prerequisites as environmental variable need to be set after the installation.

Also see some other suggestion of Nuget packages may be missing see https://github.com/microsoft/Learn-LTI/issues/161
