### ISSUE TITLE
Bad Request  -- Microsoft.KeyVault/vaults  

### ISSUE THREAD

**Issue by PedroLozano33** [microsoft/Learn-LTI#201]
Error deploying Learn-LTI tool from Azure AD 

when I run the Learn-LTI tool implementation guide it generates an error with the Key Vault, I already tried in different tenants and different subscription and is the same error:

{
     "status": "Failed",
     "mistake": {
         "code": "BadRequest",
         "message": "Invalid value found at accessPolicies[0].ObjectId: "
     }

**LMS (please complete the following information):**
 - Platfrom: [Azure, Key Vault]

 - OS: [Windows 11 Enterprise  and Windows 10 pro 22h2]
 - Browser Chrome,edge, Firefox
 - Version [Firefox 103.02]

![error kv14](https://user-images.githubusercontent.com/112036657/186546114-743c5c61-889a-4601-b434-6641c7a3eba6.jpg)
![error kv12](https://user-images.githubusercontent.com/112036657/186546136-62b2ee65-56d9-4f37-957c-8b3b684bab99.jpg)
![error kv13](https://user-images.githubusercontent.com/112036657/186546151-0527b396-3105-40fb-b96a-d4dcea5361b7.jpg)

**Comment by leestott** [comment]
Please simply downgrade your Azure CLI to v2.27

See https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli

This is a known issue which is documented in the troubleshooting guide. https://github.com/microsoft/Learn-LTI/issues/189

Specific version
To download the MSI installer for specific version, change the version segment in URL https://azcliprod.blob.core.windows.net/msi/azure-cli-.msi and download it. Available versions can be found at [Azure CLI release notes](https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli).
