### ISSUE TITLE
login.microsoftonline refused to connect

### ISSUE THREAD

**Issue by LukeDuffy98** [microsoft/Learn-LTI#206]
# Bug

For some users (about 10 %) they have an error 
"login.microsoftonline refused to connect"

when attempting to access the MS Learn content.

![image](https://user-images.githubusercontent.com/31847926/187339022-66a8ec8e-585d-41cf-b3f9-62ff0098356b.png)

This is what we expect to see

![image](https://user-images.githubusercontent.com/31847926/187339246-d0f4bb87-e0ea-4337-95e0-33388caf2d6f.png)

**LMS (please complete the following information):**
 - Platform: Moodle
 - Version 4.0
 - Installation Self Hosted 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge/Chrome inPrivate/inCognito as well as standard

The issue persists beyond PC restarts

**Comment by leestott** [comment]
@LukeDuffy98 which version of the solution are you using? is this error presented using the UCL AAD B2C fork?

**Comment by LukeDuffy98** [comment]
@leestott its with the latest UCL fork, and also with my older install. I had assumed in the past it was an issue in my configuration (as it was vey much mashed together ) but its also in a new server build.

And just like magic, its happening on my account now so I can troubleshoot. I believe I have fond the issue and a workaround, I just need to work on explaining it.:
![image](https://user-images.githubusercontent.com/31847926/187411928-4b8a328a-4b54-40e0-996f-10ed75b62a6e.png)
