### ISSUE TITLE
Content selector is empty

### ISSUE THREAD

**Issue by PedroLozano33** [microsoft/Learn-LTI#207]
I am trying to modify an activity, but when I want to bring the material from the content selector it appears blank.

can you support me please?

attached image for better detail
![Error Selec Content 0](https://user-images.githubusercontent.com/112036657/187838332-a7b2497a-c916-4aef-b71d-255bbd848f49.jpg)
![Error Selec Content 1](https://user-images.githubusercontent.com/112036657/187838363-81dea558-c656-48c2-a0c5-b0f44f06a506.jpg)
![Error Selec Content](https://user-images.githubusercontent.com/112036657/187838374-3409919e-7655-4f24-978f-f85d4d6d3fce.jpg)

**LMS (please complete the following information):**
 - Platfrom:  Moodle
 - Installation  Self Hosted IaaS 

 - OS: Windows 11 and Windows 10
 - Browser [Chrome, edge and safari]

**Comment by leestott** [comment]
@PedroLozano33 please ensure you follow the setup and configuration instructions also please confirm which version of Moodle you are using?

Moodle Configuration guide
https://github.com/microsoft/Learn-LTI/blob/main/docs/CONFIGURATION_GUIDE.md#moodle-lms

**Comment by leestott** [comment]
No update for 26 days. If the issue is still active please reopen the issue @PedroLozano33
