### ISSUE TITLE
help with https://github.com/microsoft/Learn-LTI/blob/main/docs/DEPLOYMENT_GUIDE.md

### ISSUE THREAD

**Issue by jorodas** [microsoft/Learn-LTI#210]
# If this is about an issue in the guides

**Describe the issue**
I am a Microsoft Employee (@jorodas) and my dedicated customer needs assistance with https://github.com/microsoft/Learn-LTI/blob/main/docs/DEPLOYMENT_GUIDE.md. Specifically, they mentioned this:

"Script is supposed to deploy MS Learn-LTI integration with Canvas LMS and provide links for LMS integration. The script fails to deploy the keyvault and does not provide custom URL for LMS integration. Support was able to resolve the deployment issue but using ARM, not the script, so we are unable to obtain the custom URLs for integration."

**Expected behavior**
"The script fails to deploy the keyvault and does not provide custom URL for LMS integration. Support was able to resolve the deployment issue but using ARM, not the script, so we are unable to obtain the custom URLs for integration."

**LMS (please complete the following information):**
 - Platform: Canvas
 - Version n/a
 - Installation n/a

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - Version 106.0.1370.37

**Smartphone (please complete the following information):**
 - Device: n/a
 - OS: n/a
 - Browser n/a
 - Version n/a

**Comment by leestott** [comment]
Hi, do you have any screenshot of the error? or further details of the deployment error?

**Comment by leestott** [comment]
@jorodas 

The AAD admin should simply run this script https://github.com/microsoft/Learn-LTI/blob/main/deployment/Deploy.ps1

**Comment by arnoldvilleneuve** [comment]
I have implemented the deploy.ps1 three times now and each time it has been successful. I don't use the run.bat command but rather the powershell command within it. I was a Global Admin while doing this. 

PowerShell.exe -ExecutionPolicy Bypass -File .\Deploy.ps1

Make sure you are in the Deployment folder. 

Thank you Lee for all the hard work. It is nice to see a github deployment that actually works. Well done.
