### ISSUE TITLE
Does anyone have monthly cost estimates to run the MS Learn LTI solution?

### ISSUE THREAD

**Issue by arnoldvilleneuve** [microsoft/Learn-LTI#211]
Just looking to see if others have any experience as to the average monthly cost of running the MS Learn LTI solution for say 1000 users? 

Any cost information at all would be appreciated. Trying to do some estimates for a client. 

Thank you.

**Comment by leestott** [comment]
@arnoldvilleneuve  so we expect the service to be approx $20 per month see https://github.com/microsoft/Learn-LTI/blob/main/docs/FAQ.md#cost-management
