### ISSUE TITLE
Deployment Failed

### ISSUE THREAD

**Issue by jajjaf** [microsoft/Learn-LTI#216]
I execute the script execute the file run.bat. , I select the subscription and the region.  I have this error : 

ERROR: {"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"NotFound","message":"{\r\n  \"error\": {\r\n    \"code\": \"ParentResourceNotFound\",\r\n    \"message\": \"Can not perform requested operation on nested resource. Parent resource 'kv-oiwluipgt' not found.\"\r\n  }\r\n}"},{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"BadRequest\",\r\n    \"message\": \"Invalid value found at accessPolicies[0].ObjectId: \"\r\n  }\r\n}"}]}}

**Comment by leestott** [comment]
@jajjaf 

Please ensure you have the following installed specifically the version of CLI 

To begin, you will need:

[Azure CLI](https://azcliprod.blob.core.windows.net/msi/azure-cli-2.27.0.msi) readme about [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest?WT.mc_id=academic-80547-leestott)
We currently recommend using Microsoft [Azure CLI version 2.27.0](https://azcliprod.blob.core.windows.net/msi/azure-cli-2.27.0.msi)
To download the MSI installer for specific version, change the version segment in URL https://azcliprod.blob.core.windows.net/msi/**version**.msi and download it. Available versions can be found at [Azure CLI release notes](https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?WT.mc_id=academic-80547-leestott).
[DotNet Core SDK .NET Core 3.1](https://dotnet.microsoft.com/download/dotnet/3.1?WT.mc_id=academic-80547-leestott)
[Node.js](https://nodejs.org/en/download/)
[Powershell](https://docs.microsoft.com/powershell/scripting/install/installing-powershell?view=powershell-7?WT.mc_id=academic-80547-leestott)
[Git](https://git-scm.com/downloads)
An Azure subscription

Additionally please ensure you run the deploy.ps1 with an administrator account in Powershell 

If you have further issues or error, please check the closed issues as the error you have is typically related to incorrect CLI versions.

**Comment by leestott** [comment]
To uninstall a failed deployment please follow the https://github.com/microsoft/Learn-LTI/blob/main/deployment/cleanup.bat
