### ISSUE TITLE
Learn-LTI launch page not found

### ISSUE THREAD

**Issue by trevorh13** [microsoft/Learn-LTI#223]
Hi,

I have deployed the Learn-LTI and tried to integrate with LMS365 but with no joy. Whilst I am awaiting assistance from their tech support I have tried linking a Moodle deployment to the tool as there are instructions for this is the guide here. However I am receiving a HTTP 500 error saying that the page is unable to service the request. Has anybody got any ideas on how I can proceed at this point as the issue seems to lie with learn-lti rather than the LMS and I have no idea how to troubleshoot further!

**Comment by trevorh13** [comment]
I have just learned of the cleanup.bat script. Will give this a try and start again!

**Comment by leestott** [comment]
@trevorh13  so at present we dont have configuration instructions for LMS365 it would be great if you could debug this based on the Moodle, Canvas, OpenEdx and Blackboard instructions and then contribute instructions back to the repo. 

I would suggest you remove the application using the cleanup script and ensure reinstall. https://github.com/microsoft/Learn-LTI/blob/main/deployment/cleanup.bat

**Comment by trevorh13** [comment]
Hi Lee,

Thank you for getting back to me. The truth is I am about at my wits end trying to get the Learn-LTI to install. I have cleaned up both manually and using the script, tried the earlier dot net release recommended etc, as well as later ones.  Currently with dotnet v3.1 the installation is failing at the point it updates the key vault – namely it tells me it can’t update the  nested resource. If I look in Azure Portal I notice that no key vault has been created. I have tried using a new Resource group, and also the alternative method of amended the unique ID within the JSON file, but doing that throws an error about being unable to parse the JSON file.

Any ideas? Have to confess my scripting skills are next to non-existent.

Kind Regards,

Trevor Hopkins
AEB, Quality and Safeguarding Lead
JBC Skills Training Ltd
07870 212536 / 024 76999425
***@***.***
www.jbctraining.co.uk   [cid:jbcsafeguarding258x175_3_bc0f7403-3ef4-47ef-af67-216e23f0ef04.png] <http://safe.jbcmail.com> <http://safe.jbcmail.com>
[cid:facebook_32x32_946fac37-a220-4178-8488-d876ffdb4649.png]<https://www.facebook.com/jbctraining>  <https://www.linkedin.com/company/jbctraining> [cid:linkedin_32x32_2411b39d-053c-4b15-9251-ec07651037ce.png] <https://www.linkedin.com/company/jbc-skills-training>   [cid:instagram_32x32_38ac0724-596d-494b-8ba6-748d748a57eb.png] <https://www.instagram.com/jbctraining>   [cid:twitter_32x32_155afc3d-6535-4b0c-8fa5-4931c39468e9.png] <https://www.twitter.com/jbctraining>

JBC Skills Training Ltd places the highest priority on the security and privacy of our Clients. The content of this email is for the intended recipient only, should you believe you have received this email in error, please notify the sender immediately and delete it. Whilst we have taken reasonable steps to ensure that this message is free of errors and viruses, we recommend that you always scan emails for any threats with your own suitable software, as we cannot accept liability for any damage inflicted by viewing the content of this email. If you have any feedback on any aspect of the service we have provided, we would like to hear from you via an email to ***@***.******@***.***>
