### ISSUE TITLE
Issue installing client - npm fixup

### ISSUE THREAD

**Issue by trevorh13** [microsoft/Learn-LTI#224]
I am trying to install this and am receiving the following issue at Step 12.

Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db

I've tried doing as it suggests, and it explains that there are issues with dependencies. I have tried keeping the legacy dependencies and updating them and however the error is still thrown when I try a redeployment.

Any ideas?

**Comment by leestott** [comment]
@trevorh13 please ensure you have the following prerequisite installed 
[Azure CLI](https://azcliprod.blob.core.windows.net/msi/azure-cli-2.27.0.msi) readme about [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest?WT.mc_id=academic-80547-leestott)
We currently recommend using Microsoft [Azure CLI version 2.27.0](https://azcliprod.blob.core.windows.net/msi/azure-cli-2.27.0.msi)
To download the MSI installer for specific version, change the version segment in URL https://azcliprod.blob.core.windows.net/msi/**version**.msi and download it. Available versions can be found at [Azure CLI release notes](https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?WT.mc_id=academic-80547-leestott).
[DotNet Core SDK .NET Core 3.1](https://dotnet.microsoft.com/download/dotnet/3.1?WT.mc_id=academic-80547-leestott)
[Node.js](https://nodejs.org/en/download/)
[Powershell](https://docs.microsoft.com/powershell/scripting/install/installing-powershell?view=powershell-7?WT.mc_id=academic-80547-leestott)
[Git](https://git-scm.com/downloads)
An Azure subscription

Please ensure you run the https://github.com/microsoft/Learn-LTI/blob/main/deployment/cleanup.bat to remove any failed deployments before running the setup again.
