### ISSUE TITLE
Outdated CLI Commands

### ISSUE THREAD

**Issue by jlan90** [microsoft/Learn-LTI#226]
# If this is about an issue in the guides

**Describe the issue**
Azure CLI now uses graph for API calls instead of each service having their own CLI commands.
When running run.bat, the deployment onto azure finishes but there are commands that error and cannot be run due to the CLI being updated and commands now depreciated.

**Expected behavior**
The deploy script should deploy resources to azure and run CLI commands without errors.

**LMS (please complete the following information):**
Not at that stage
 - Platfrom: [OpenEdx - Tutor]
 - Version [N/A]
 - Installation [EKS deployment]

**Desktop (please complete the following information):**
 - OS: [ Windows
 - Browser [edge]

**Comment by leestott** [comment]
Yes please use the specific version of the CLI https://github.com/microsoft/Learn-LTI/blob/main/docs/DEPLOYMENT_GUIDE.md 

States 
[Azure CLI](https://azcliprod.blob.core.windows.net/msi/azure-cli-2.27.0.msi) readme about [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest?WT.mc_id=academic-80547-leestott)
We currently recommend using Microsoft [Azure CLI version 2.27.0](https://azcliprod.blob.core.windows.net/msi/azure-cli-2.27.0.msi)
