### ISSUE TITLE
Learn LTI unable to confirm user is enrolled on Module

### ISSUE THREAD

**Issue by pdaniel1-salford** [microsoft/Learn-LTI#233]
Hi,

I am attempting to install Learn LTI and set it up to work with Blackboard SAAS and have successfully deployed the system but not getting it working. I have since removed the deployment and re-deployed in the hope that by updating the software it would fix something as I am unable to debug the reason for the problem.

I am able to get to the point of starting a Learn LTI from within Blackboard, but no matter what I do, I am unable to convince Learn that I am enrolled on module, have logged in with my AAD account and that my email matches.

When debugging the Azure I can see it has successfully run the GetUserDetails Function and got a successful response from Blackboard. However whatever that response contains, it doesn't include me as a member or the course.

As this is a black box to me I am unable to progress this further on my own and hope you can help me uncover what is misconfigured or missing.

Kind regards
Paul

**Comment by leestott** [comment]
@pdaniel1-salford Thanks for reaching out so did you follow https://github.com/microsoft/Learn-LTI/blob/main/docs/CONFIGURATION_GUIDE.md#blackboard-learn-lms 

Can you confirm the version of Blackboard also is your Blackboard using AAD signin? 
Ensure your username email is the same in both sides as per the troubleshooting guide.

**Comment by leestott** [comment]
@pdaniel1-salford can you share any screenshot of error etc?

**Comment by pdaniel1-salford** [comment]
Hi Lee,

Thanks for your help so far.

As we have been corresponding via email, I hadn't realised the case had been closed. Unfortunately the LTI is still not working and I really need to have this escalated or discover if there is a fault with the LTI.

Kind regards
Paul
