### ISSUE TITLE
cannot access the application 'd41fd017-4c7d-4867-ac93-3cac32d3f7a9'

### ISSUE THREAD

**Issue by MathieuHoude** [microsoft/Learn-LTI#234]
**Describe the issue**
In the deployment guide, when I access the tool registration page, I get the following error:
_Selected user account does not exist in tenant 'Microsoft' and cannot access the application 'd41fd017-4c7d-4867-ac93-3cac32d3f7a9' in that tenant. The account needs to be added as an external user in the tenant first. Please use a different account._
![Capture d’écran 2023-02-21 224717](https://user-images.githubusercontent.com/28630658/220516693-d59d8164-46c3-48c3-aa68-3c434d29e179.png)
The deployment script runs without any error.
The account used is the owner of the subscription to which the tool was deployed.

**Expected behavior**
To be able to finish the deployment process by accessing the tool registration page.

**Comment by MathieuHoude** [comment]
If it can help somebody else, after many, many debugging hours I finally found out the issue.

Using:
dotnetcore 3.1
azure-cli 2.27
nodejs 18.14.2
The important part: Powershell **7** (the script was not working with Powershell 5)

Also, with the script as is, I was getting the following error
```
ParentResourceNotFound {
"status": "Failed",
"error": {
"code": "BadRequest",
"message": "Invalid value found at accessPolicies[0].ObjectId: "
}
}
```
The source of this issue is in the Deploy.ps1 file:
`$userObjectId = az ad signed-in-user show --query id`
should be
`$userObjectId = az ad signed-in-user show --query objectId`

Even though I use the exact version mentioned in the deployment guide, I guess that something changed in the azure cli.

**Comment by leestott** [comment]
Thanks for the confirmation.  We will add this to the troubleshooting guide.
