### ISSUE TITLE
Problems going through this process

### ISSUE THREAD

**Issue by brockettc** [microsoft/Learn-LTI#237]
First error I receive when trying to go to the URL given at the end of the Azure autoconfigure scripts. 

'asked for scope 'user_impersonation' that doesn't exist.'

I followed this to fix it (https://robertschouten.com/2019/06/19/user_impersonation-scope-issue-when-working-with-sharepoint-framework-api-permissions/) - whether that's the right or wrong approach. 

Next error was no user id_token. 

I followed this to fix it (https://stackoverflow.com/questions/49422588/aadsts70005-response-type-id-token-is-not-enabled-for-the-application) - whether that's the right or wrong approach.

The next error that I get and I have yet to find a solution for is... AADSTS500113: No reply address is registered for the application.

What should the reply address be? 

Thanks,

Chris

**Comment by leestott** [comment]
Can I suggest you unistall the solution ensure your running the versions below - Ensure your running the command from the specific version of the Azure CLI 

To begin, you will need:

[Azure CLI](https://azcliprod.blob.core.windows.net/msi/azure-cli-2.27.0.msi) readme about [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest?WT.mc_id=academic-80547-leestott)
We currently recommend using Microsoft [Azure CLI version 2.27.0](https://azcliprod.blob.core.windows.net/msi/azure-cli-2.27.0.msi)
To download the MSI installer for specific version, change the version segment in URL https://azcliprod.blob.core.windows.net/msi/**version**.msi and download it. Available versions can be found at [Azure CLI release notes](https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?WT.mc_id=academic-80547-leestott).
[DotNet Core SDK .NET Core 3.1](https://dotnet.microsoft.com/download/dotnet/3.1?WT.mc_id=academic-80547-leestott)
[Node.js](https://nodejs.org/en/download/)
[Powershell](https://docs.microsoft.com/powershell/scripting/install/installing-powershell?view=powershell-7?WT.mc_id=academic-80547-leestott)
[Git](https://git-scm.com/downloads)
An Azure subscription

**Comment by leestott** [comment]
Please follow 
https://github.com/microsoft/Learn-LTI/blob/main/docs/DEPLOYMENT_GUIDE.md - Deployment Guide
https://github.com/microsoft/Learn-LTI/blob/main/docs/CONFIGURATION_GUIDE.md - Configuration Guide
