### ISSUE TITLE
Problem on re-deployment

### ISSUE THREAD

**Issue by paprodziad** [microsoft/Learn-LTI#238]
We are trying to re-deploy and received the following error in step 6: “ERROR: {“error”:{“code”:”DeploymentNotFound”,”message”:”Deployment ‘Deployment-10-04-2023-11-46-38’ could not be found.”}}

I noticed that the Cleanup.ps1 states: 'Please use a different ResourceGroup name on re-deployment!'. Am I correct to assume that we should modify the $ResourceGroupName param in the Deploy.ps1 to be able to successfully re-deploy?

**Comment by leestott** [comment]
Hi simply ensure you remove all the resources and resource group and ensure you purge the keyvault if rerunning the setup please also ensure your using the specific version of the Azure CLI on the install to ensure no errors.
