### ISSUE TITLE
XHR request to /me returns 204 no content using LTI 1.1

### ISSUE THREAD

**Issue by porcospino** [microsoft/Learn-LTI#52]
# Bug

Using Moodle 3.5.10+, which only supports LTI 1.0/1.1

As a Moodle administrator, follow the [CONFIGURATION_GUIDE.md](https://github.com/microsoft/Learn-LTI/blob/main/docs/CONFIGURATION_GUIDE.md#moodle-lms).

As a Moodle "Teacher" in a course, follow instructions in the USER_GUIDE.md

I get to [step 7](https://github.com/microsoft/Learn-LTI/blob/main/docs/USER_GUIDE.md#Customize-Review-and-Publish-the-assignment) and expect to see something similar to the screenshot.  Instead I see a message saying "Loading assignment"

Developer Tools reveals the XHR request to `https://users-xxxxxxxxx.azurewebsites.net/api/assignments/XXXXXX==_XXXXXX=/me` returns `204 No Content`

The Moodle "Teacher" account has an email address matching both the "mail" and "User Principal Name" values in Azure Active Directory

**Desktop:**
 - OS: Ubuntu 20.04.1 LTS
 - Browsers: Chromium Version 85.0.4183.83 and Firefox 80.0.1

**Comment by adbindal** [comment]
Thanks @porcospino for the update. I'm closing the issue based on the above update.
