### ISSUE TITLE
Microsoft Learn LTI application not working

### ISSUE THREAD

**Issue by koolala** [microsoft/Learn-LTI#55]
LMS: Moodle 3.8.3
Login Account: (Deploy the App and has Moodle Admin Right)

Cases:
When I process to open LTI link.
https://github.com/microsoft/Learn-LTI/blob/main/docs/USER_GUIDE.md#Customize-Review-and-Publish-the-assignment

The page has an Error. 
https://learnclientuxi3dtbbn.z7.web.core.windows.net/Mzk=_Ng==#
![image](https://user-images.githubusercontent.com/3178741/93466979-ab368200-f91f-11ea-85b1-9319a8add1d4.png)

Additional Information:
![image](https://user-images.githubusercontent.com/3178741/93483432-61f02d80-f933-11ea-9ebc-4fc110d2bcd5.png)

**Comment by adbindal** [comment]
Hi @koolala,

Thanks a lot for reporting the issue. The failure of the API indicates that `Users` Function App is not working as expected, most probably there's a crash that happened on the server. I'd recommend doing the following to understand the Azure function behavior and helping us with the details.

## Troubleshooting
### Azure Function Traces
- Goto your Resource Group inside Azure and select **Function App** matching `users-XXXXXXX`.
- Select **Functions** Blade in Left Hand Pane. Select `GetUserDetails` afterwards.
- Choose **Monitor** Blade in LHP and you should see the **Invocation Traces**.
- Clicking on the failing trace should provide more details related to Server logs for that function invocation to help you.
### Failures (Exceptions) in App Insights
- Go to your Resource Group inside Azure and select **Application Insights** resource matching `users-XXXXXXX`.
- Select **Failures** Blade in LHP and then choose **Exceptions** Tab.
- The subsequent screen should indicate any exceptions that were thrown as a part of function execution and should provide more insights into what might've gone wrong on server when executing `GetUserDetails` api.

> We'd request you to please share the above details with us in order for us to be able to help you in a better way. Since the details might contain some private information as well. Please feel free to reach out to us via email at [learnlti@microsoft.com](learnlti@microsoft.com).

**Comment by koolala** [comment]
@adbindal 
Thanks for your help.

The problem has been solved.

**An Unauthorized (401) Exception** occurred when access the **Moodle's LTI services**.
/mod/lti/services.php/CourseSection/39/bindings/2/memberships

The problem came from the Apache Config.

**Solution**
https://moodle.org/mod/forum/discuss.php?d=389429
