### ISSUE TITLE
Adding LTI Activity Moodle

### ISSUE THREAD

**Issue by LukeDuffy98** [microsoft/Learn-LTI#62]
Hi

When trying to configure a newly added LTI activity in Moodle, I receive the error :
You are not enrolled in this course.

I am following the steps https://github.com/microsoft/Learn-LTI/blob/main/docs/USER_GUIDE.md#Create-an-assignment-in-Moodle-leveraging-Microsoft-Learn-LTI-application

and I am at step 7.

I am expecting to see a page similar to : https://github.com/microsoft/Learn-LTI/blob/main/docs/USER_GUIDE.md#Customize-Review-and-Publish-the-assignment

I believe everything is configured correctly.
![image](https://user-images.githubusercontent.com/31847926/94229941-2b726e00-ff44-11ea-8343-30ad6bab348e.png)

Thanks

**Comment by adbindal** [comment]
Hi @LukeDuffy98 ,

Thanks a lot for reporting the issue. As stated, the failure is in `Users` Function App which is not being able to find the user (signed-in via AAD) enrolled into the current course. To prove this theory, please check that the return code for `/me` API in the Chrome DevTools network tab is `http204` (i.e. `No-Content`).

- As a quick question, could you please let us know whether your tool is onboarded using **LTI1.1** or **LTI1.3**?
- In our experience, as I remember, the only case when this happens is when user signs into Learn-LTI app with an `onmicrosoft.com` account which does not map to the email of any of the enrolled users of the course.

Additionally, you could use the following steps to understand the Azure function behavior and help us with the more details on your issue.

## Troubleshooting
### Azure Function Traces
This should provide details related to the execution context and state of the function execution when it would've returned `http204`.
- Goto your Resource Group inside Azure and select **Function App** matching `users-XXXXXXX`.
- Select **Functions** Blade in Left Hand Pane. Select `GetUserDetails` afterwards.
- Choose **Monitor** Blade in LHP and you should see the **Invocation Traces**.
- Clicking on the failing trace should provide more details related to Server logs for that function invocation to help you.
### Failures (Exceptions) in App Insights
- Go to your Resource Group inside Azure and select **Application Insights** resource matching `users-XXXXXXX`.
- Select **Failures** Blade in LHP and then choose **Exceptions** Tab.
- The subsequent screen should indicate any exceptions that were thrown as a part of function execution and should provide more insights into what might've gone wrong on server when executing `GetUserDetails` api.

> We'd request you to please share the above details with us in order for us to be able to help you in a better way. Since the details might contain some private information as well. Please feel free to reach out to us via email at [learnlti@microsoft.com](learnlti@microsoft.com).

**Comment by koolala** [comment]
HI @LukeDuffy98

I had this message before.
In my case, my account (admin right) has not enroll to the Moodle's course.  Then, I enrolled my account as a Trainer. 

After enrolled, the LTI application page will show the content.
![image](https://user-images.githubusercontent.com/3178741/94397091-b8603600-0195-11eb-9e76-f0213684c1aa.png)

**Comment by LukeDuffy98** [comment]
Hello,

It appears that as soon as I had Azure AD connected accounts then it was fine.

So if I did a vanilla Moodle install without any AAD then it wasn’t working. When I enable AAD then it was able to proceed.

Thanks

Luke Duffy
03 9028 8949 – Melbourne
03 6234 3883 - Hobart
0414 411 827
www.v-learn.com.au<https://apac01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.v-learn.com.au%2F&data=02%7C01%7Clgeorge%40casey.vic.gov.au%7C399a02907ba24103beec08d52c8e3d7c%7C44a029424e5b420a8bc4f60b91281f2e%7C1%7C0%7C636463912313350514&sdata=io0PfcuTT9CdIRhwOFfQlqxcXpl2TzYKArF3Dje3ixE%3D&reserved=0>
www.quill.com.au<https://apac01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.quill.com.au%2F&data=02%7C01%7Clgeorge%40casey.vic.gov.au%7C399a02907ba24103beec08d52c8e3d7c%7C44a029424e5b420a8bc4f60b91281f2e%7C1%7C0%7C636463912313350514&sdata=FLIvTTdBhJpnhNIRNwJUQg77w9vfX%2FRxlifaeW1vcrY%3D&reserved=0>

Follow me on LinkedIn<https://www.linkedin.com/in/luke-duffy-1661335/>
[cid:image001.png@01D695B6.0389B030][cid:image002.jpg@01D695B6.0389B030][cid:image003.jpg@01D695B6.0389B030]
[logo]
[cid:image005.gif@01D695B6.0389B030]


The Quill Consultancy wants to help you, we are offering low priced courses that lead to valuable Microsoft certifications to everybody.
https://quill.com.au/our-response-to-covid-19/

https://quill.com.au/microsoft-365-certified-enterprise-administrator-expert/
