### ISSUE TITLE
Moodle with LTI 1.1

### ISSUE THREAD

**Issue by oyara** [microsoft/Learn-LTI#67]
I am trying to integrate Learn LTI with my corporate Moodle. I have deployed correctly all the elements in Azure but I cannot continue because I am using LTI 1.1 in Moodle and I don't know where I can find Customer Secret and Shared Secret after finish the deployment. I have all the information for configure with LTI 1.3 but no with LTI 1.1

![image](https://user-images.githubusercontent.com/1382584/94732225-43902600-0366-11eb-92b4-323e7cac766d.png)

**Comment by leestott** [comment]
@oyara Hi so the Key and Secret are from step1. https://github.com/microsoft/Learn-LTI/blob/main/docs/DEPLOYMENT_GUIDE.md when you deploy the service into your Azure Subscription. 

Can you confirm if this resolves your issue

**Comment by techulabs** [comment]
Thanks @leestott 
I thought that I would need to obtain Consumer key and Shared secret from some place in Azure deployment. 
I'll try with "key" and "secret".

Regards.

**Comment by oyara** [comment]
Thanks @leestott 
I thought that I would need to obtain the Consumer key and Shared secret from some place in Azure deployment.

I'll try with "key" and "secret".

Regards.
