### ISSUE TITLE
Brightspace

### ISSUE THREAD

**Issue by skmckenFVSD** [microsoft/Learn-LTI#68]
Is there any deployment Guide to use within Brightspace as yet?

**Comment by leestott** [comment]
Hi @skmckenFVSD not yet but if you like to work through the Moodle/Canvas guides and develop and contribute instructions this would be great for the community.

**Comment by leestott** [comment]
@alphaz18 thanks for PR regarding the outh support for Brightspace D2L https://github.com/microsoft/Learn-LTI/pull/156 

Could you also help us develop setup/config guides for D2L and PR changes for https://github.com/microsoft/Learn-LTI/blob/main/docs/CONFIGURATION_GUIDE.md to include D2L

**Comment by leestott** [comment]
@skmckenFVSD please could you help validate if this implementation for Brightspace D2L works on your implementation https://github.com/microsoft/Learn-LTI/pull/156

**Comment by leestott** [comment]
@skmckenFVSD please could you help validate if this implementation for Brightspace D2L works on your implementation https://github.com/microsoft/Learn-LTI/pull/156

**Comment by skmckenFVSD** [comment]
@leestott Do you have any Guidance on adding it to Brightspace as yet?
