### ISSUE TITLE
Wrong link for Architecture Overview doc

### ISSUE THREAD

**Issue by yanxiaodi** [microsoft/Learn-LTI#73]
# If this is about an issue in the guides

**Describe the issue**
The link of `Architecture Overview` is wrong. 
On this page: https://docs.microsoft.com/en-us/learn/support/lti-application, the link of `Architecture Overview` is https://aka.ms/LearnLTI-Repo-Docs5. If I click the link, it navigates to https://github.com/microsoft/Learn-LTI/blob/main/docs/ARCHITECTURE_OVERVIEW.md), not https://github.com/microsoft/Learn-LTI/blob/main/docs/ARCHITECTURE_OVERVIEW.md.

Because it uses Microsoft short url so I cannot create the PR to fix it. Please remove the useless ")". Thanks.

**Expected behavior**
The link of `Architecture Overview` should navigate to the correct document.

**Comment by adbindal** [comment]
Thanks @yanxiaodi for reporting the issue. We'll get the short-url fixed and update the thread.

**Comment by leestott** [comment]
Hi Sorry changes were wrong in link https://github.com/microsoft/Learn-LTI/blob/main/docs/ARCHITECTURE_OVERVIEW.md)

The additional ) needs removing from the url.

**Comment by adbindal** [comment]
Hi @yanxiaodi, we have updated the **aka.ms** link to remove extraneous `)` in the redirect url. Thanks a lot for reporting the issue.
