### ISSUE TITLE
SSO with azure AD

### ISSUE THREAD

**Issue by CasperNaudts** [microsoft/Learn-LTI#74]
Would love to have a guide in the docs for AAD SSO.

**Comment by adbindal** [comment]
Hi @CasperNaudts 

Thanks for using our Learn-LTI Tool. While we would work towards improving our documentation for AAD SSO, we could use this opportunity to understrand your use case in more detail and probably what specific aspect of AAD SSO you are looking an improvement for.

**Comment by CasperNaudts** [comment]
Hi @adbindal 

Thanks for the quick response. At our school we almost exclusively use MS-teams for everything related to exchanging information between teacher and student. For our it courses we have been looking for a platform that allows the teacher to publish their own content related to hardware and so but for the software part we want an interactive environment. We already use MS learn but don't like the options for own content.

Our main goal is to let our students sign in with there office 365 login, and if posible get some MS-teams integration.

I am looking for a step by step guide to connect the SSO experience with AAD. I have a good knolage of azure services, but I am not a hero at applications in AAD.

thanks for the support

**Comment by adbindal** [comment]
Hi @CasperNaudts 

I checked with the team and please see if the details provided at https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/plan-sso-deployment aligns to your requirement. We'd also request you to reach us out via our email learnlti@microsoft.com to better understand your use case and provide relevant recommendations to you.

Thanks a lot for trying to use our product in your environment.

**Comment by adbindal** [comment]
Closing the issue since it has not seen any activity for over a week now.
